tangrams/tangram

src/leaflet_layer.js, src/scene.js, src/subscribe.js
Looks like we are finally succumbing to the need to have some kind of event subscribe system. Here's an attempt at a minimal one.
=> Minimal event system

demos/styles.yaml, src/styles/style_parser.js
Hooks into https://github.com/tangrams/unruly/pull/1
=> Pass style properties to filter functions

karma.conf.js, makefile, package.json, test/helpers.js
Much more helpful output and will help identify possible GL or network bottlenecks that may be causing frequent Sauce Labs disconnect errors.
=> Use Mocha reporter for tests

package.json, src/gl/shader_program.js, src/gl/texture.js, src/gl/vao.js, src/gl/vbo_mesh.js, src/gl/vertex_data.js, src/scene.js, src/selection.js, src/styles/builders.js, src/styles/text/label.js, src/vector.js, test/helpers.js
More consistent with the newer parts of the codebase, and I needed to do something for a few hours that didn't require a lot of brainpower.
=> Convert serveral modules to classes & restore VAO support

src/gl/render_state.js, src/scene.js
Lazy setup for render states to reduce driver state changes.
=> GL Render states

demos/main.js, package.json, src/gl/shader_program.js, src/gl/texture.js, src/scene.js, src/styles/style_manager.js
Adds initial error and warning events triggered by the `scene` object, which can be subscribed to by a Tangram client. These can be used to surface better feedback about scene config issues (such as when a data source is improperly configured, or a style's shaders fail to compile) -- the first expected use here is Tangram Play. Events receive a single object as an argument, with event-specific properties.
`scene` will emit these event types:
- `load`: scene successfully loaded, arguments:
- `config`: the scene config object
- `error`: scene failed to load, arguments:
- `message`: human-readable description
- `type`': for now, only `yaml` for YAML validation errors (TODO: add more error types)
- `error`: the Error object with further details (for YAML validation issues, can extract info on …
=> Add error and warning events

src/scene.js
per https://github.com/tangrams/tangram/issues/174
=> trim duplicate variable declarations

src/styles/style_manager.js
This prevents shader blocks that have already been mixed in from an ancestor style from being mixed a second time.
This supports a 'diamond'-like mixin hierarchy where:
```
A
/ \
/   \
B     C
\   /
\ /
D
```
In this case (or more complex ones like it where a style is mixed into multiple ancestors), style `D` should end up with only one copy of style `A`.
Note: one thing I am not entirely pleased with in this solution is that it only applies explicitly to shader blocks. Because mixing the same style multiple times does not cause breakage for any properties other than shader blocks, this may be an acceptable approach for now. It could raise some potential issues with order of mixin application, since shader blocks will be mixed in the order of the first parent found, while later mix …
=> Only mix each ancestor style once

src/gl/shaders/material.glsl, src/light.js, src/material.js, src/scene.js, src/styles/points/points_fragment.glsl, src/styles/points/points_vertex.glsl, src/styles/polygons/polygons_fragment.glsl, src/styles/polygons/polygons_vertex.glsl, src/styles/style_manager.js
Matching @blair1618 fix of glsl global init bug https://github.com/tangrams/tangram-es/commit/63120ab16910ea7dfd91dbb1c2374f0b0699f5c7#commitcomment-14197819
=> matching tangram-es glsl fix for globals init

src/sources/geojson.js, src/sources/mvt.js
The next rev of the MVT format (https://github.com/mapbox/vector-tile-spec/) clarifies how multipolygons should be encoded: as a single "flattened" series of rings, where individual polygons can be extracted by examining the winding order of each to determine inner/outer rings; a new polygon starts each time an outer ring is found.
We are already doing this for polys generated by geojson-vt. Now we are also applying it to MVT tile sources. This is backwards compatible with our current tiles, and forwards compatible with https://github.com/mapzen/mapbox-vector-tile/pull/21.
=> Apply multipolygon ring decoding to MVT sources

src/gl/shader_program.js, src/gl/texture.js, src/scene.js, src/scene_loader.js, src/selection.js, src/styles/points/points.js, src/styles/text/text.js
Dynamically change textures using an ```url```/```image```/```canvas```/```data``` by providing one of this on the ```scene.config.textures```.  Ex:
```
scene.config.textures.orbits.url = "http://..../image.png";
scene.updateConfig({ rebuild: true });
// or
var canvas = new document.createElement("canvas");
...
scene.config.textures.orbits.element = canvas;
scene.updateConfig({ rebuild: true });
// or
var image = new document.createElement("image");
...
scene.config.textures.orbits.element = image;
scene.updateConfig({ rebuild: true });
// or
var raw_data = { data: [], width: 500, height: 500 }
...
scene.config.textures.orbits.data = raw_data;
scene.updateConfig({ rebuild: true });
```
=> Set texture

src/gl/texture.js, src/scene.js, src/sources/data_source.js, src/styles/points/points.js, src/styles/style.js, src/styles/style_manager.js, src/styles/text/text.js, src/tile.js, src/tile_manager.js
This PR extracts some changes that were originally made as part of full raster tile support in #247. We're not yet ready to merge that full PR, but there are refactors and other changes that were made in support of raster tiles, that I would like to merge into master now, to ease coordination with other impending branches.
This PR has no impact on user-facing functionality.
=> Raster tile preparation

src/light.js
As @meetar suggest ```Point Lights``` default to 
```
origin: ground
position: [0, 0, 100]
```
=> point lights defaults to what peter suggest

demos/styles/windows.yaml, demos/styles/wood.yaml, src/styles/polygons/polygons_fragment.glsl, src/styles/polygons/polygons_vertex.glsl
Update lighting block behavior to match https://github.com/tangrams/tangram/issues/257.
=> Fix lighting blocks

CONTRIBUTING.md, circle.yml, package.json
This PR 
* updates the `CONTRIBUTING.md` file with the new npm script workflow
* `npm start` script aliases the watcher
* `npm test` sets up local testing, and a `circle.yml` file overrides the Circle CI's test command to `npm run test-ci`
* Adds @dmvaldman as a contributor ;-)
=> Contributing

src/builders/polylines.js
This PR has a fix for the errors spotted in https://github.com/tangrams/tangram/issues/323
Specifically this PR handles orientation (clockwise vs counterclockwise) for joins, which wasn't taken into account previously. This was actually the cause of the weirdness spotted in #323
=> Fix for polygon boundary lines

src/scene.js
Tangram loads any custom data source scripts into web workers at the time of worker instantiation, in a single `importScripts()` call along with itself. This method has mostly been settled on as the most reliable, with the loading of large scripts (like Turf.js) into web workers at run-time flaky on some browsers.
However, the previous code only did this when workers were initially created, meaning that loading any subsequent scenes that had *different* custom scripts (or if the initial scene had no custom scripts, followed by loading a scene that did include them) would fail.
This PR instead checks to see if a newly loaded scene has different custom scripts from those previously loaded, and if so, simply destroys and re-creates the web workers (this was the simplest way to accomplish …
=> Re-initialize web workers when data source custom scripts change

src/utils/utils.js
Some versions of Edge/IE11 have an intermittent crash when web workers issue XHRs. This is manifested by the worker ceasing to respond to any further messages from the main thread (e.g. `worker.postMessage()` calls). 
In the cases we've seen, this is actually observed as Tangram only working on *every other page reload* (in half of the cases, the workers fail to fully initialize and no tile loading or rendering occurs). 
This issue can be worked around by proxying any network requests that the worker would usually make through the main thread instead. 
This is recognized as a regression by the Edge team and reported fixed in the next version - we can verify the fix and may deprecate this workaround in the future. More info:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issu …
=> Fix intermittent crashes on Edge/IE11

src/styles/points/points.js
Continue [#508](https://github.com/tangrams/tangram/pull/508)
=> outline: make outline api consistent with lines

src/builders/points.js, src/styles/points/points.js, src/styles/points/points_fragment.glsl, src/styles/points/points_vertex.glsl, src/styles/style_parser.js, src/styles/text/text.js
=> Add point outline (rebased)

src/sources/data_source.js
Adds the ability for data sources to specify an optional list of subdomains to round-robin between, using the following syntax:
```
sources:
source-name:
type: MVT
url: https://{s}.some-tile-server.com/{z}/{y}/{x}.pbf
url_subdomains: [a, b, c, d]
```
For example, the above would cause the following hosts to be used for tile requests:
`https://a.some-tile-server.com/{z}/{y}/{x}.pbf`
`https://b.some-tile-server.com/{z}/{y}/{x}.pbf`
`https://c.some-tile-server.com/{z}/{y}/{x}.pbf`
`https://d.some-tile-server.com/{z}/{y}/{x}.pbf`
See #445 for discussion.
=> Data sources can specify optional subdomain list

demos/main.js
Added hindi in language drop down, will be useful for some shaped text testing.
Fact: I can read hindi :D
=> Add hindi language (useful for shaped text testing)

demos/main.js
Change url params from comma separated to slash separated and with zoom first, not last
=> Change url params in demo

src/builders/polylines.js, src/labels/label_line.js, src/labels/point_placement.js, src/styles/points/points.js, src/styles/points/points_vertex.glsl, src/styles/text/canvas_text.js
To everything - turn, turn, turn.
=> Comments on the code

src/styles/text/canvas_text.js
Let's do this (Arabic, Hebrew, and Divehi (Maldives) labels)
In Arabic text, some letters join to the left, and others don't. (Australia =  أستراليا for a reference). These letters are common and consistent, so we can reliably split a word on them without splitting the baseline. The only additional concern is making sure that any vowel-marks for the letter don't get split off and put at the start of the next segment. 
TODO on this: bidirectional / bilingual text. Potentially replacing with a good RegEx if we can find it
Hebrew and Divehi won't use this splitter - instead I'm just adding their vowel-marks to the code from last curved labels code
=> Split Arabic text for curved labels

src/styles/points/points.js
=> reverting c86e7f5

src/scene.js
Implements zoom interpolation for `scene.background.color`, to match https://github.com/tangrams/tangram-es/pull/1885/.
=> Support zoom stops for scene background color

src/tile/tile.js
**NOTE: description updated to reflect PR discussion.**
This PR introduces a "wildcard" syntax for the source `layer` in the `data` block in `layers`. When the parameter `all_layers: true` is included, it will match ALL layers in the data source. 
This is useful for easily creating wireframe-like views, without knowing or needing to specify all the layers in the data source:
```
layers:
wireframe:
data: { source: tilezen, all_layers: true }
draw:
lines:
color: red
width: 1.5px
order: 1
points:
color: yellow
size: 4px
collide: false
```
This parameter takes precedence over `layer`. If both `all_layers: true` and a value for `layers` are specified, then a warning is logged, `all_layers: true` is used, and the value of `layer` is ignored. Note that *other* values of `all_layers` …
=> Add `all_layers: true` wildcard for data source layer matching

src/styles/text/text_labels.js
The default `repeat_distance` for labels has always been `256px` across the board. This is a sensible default for cases such as street labels (the original use case for repeat label culling) and road shields, but can generate unexpected results particularly when applied to point labels.
For example, when labelling data with a property that has a finite set of values, such as category names ("bar", "restaurant", "hardware store", etc.) or numeric values, it's often surprising/undesirable that only a few labels are plotted.
This branch changes this behavior such that:
- For labels generated **from point features**, the default `repeat_distance` is `0px`.
- For **all other labels**, including those generated **from line or polygon features** (e.g. street names, road shields, park names, …
=> Change default `repeat_distance` for point feature labels

package.json
Updating geojson-vt for performance and edge-case handling improvements. Passed all Differ tests with only very minor changes to text – if anything it's made text sharper?
=> update geojson-vt to ^3.2.1
