- demos/styles.yaml
- makefile
- src/camera.js
- src/leaflet_layer.js
- src/scene.js
- src/tile.js
- test/helpers.js
- test/leaflet_layer_spec.js
- test/scene_spec.js
- test/tile_spec.js
Let Tangram calculate which tiles to load internally, to reduce coupling to Leaflet. 
This was motivated (at the current moment) by a desire to try different fractional zoom logic than what Leaflet does (which is to round to the nearest zoom level). Rounding is a good default, but other alternatives (like taking the zoom floor) should also be explored. 
De-coupling also makes future view features (rotation, tilt, etc.) possible (or at least easier to implement).
> De-couples tile loading from Leaflet

- demos/main.js
- demos/styles.yaml
- src/gl/texture.js
- src/scene.js
- src/scene_worker.js
- src/styles/polygons/polygons.js
- src/styles/sprites/sprites.js
- src/styles/sprites/sprites_fragment.glsl
- src/styles/sprites/sprites_vertex.glsl
- src/styles/style.js
- src/styles/style_manager.js
This removes some style-oriented texture support that I was never entirely comfortable with up to the scene level. This should be more compatible with @patriciogonzalezvivo's forthcoming material textures (https://github.com/tangrams/tangram/pull/112), and follows a suggestion from @meetar to provide a centralized way to define textures in the scene config file.
For cases where the standard material texture isn't enough (e.g. styles like sprites, that aren't doing normal texture mapping + lighting), there are now 3 ways a texture can be added to a style:
the simplest way to add a new texture is to simply refer to it by URL. For an example `icons` style, this can be done like this:
```
styles:
icons:
texture: path/to/image.png
...
```
This will automatically load `path/to/image.png`, with …
> Move style textures to the scene level

- .editorconfig
This is a real simple change to add an .editorconfig file.
http://editorconfig.org/
Basically, it just sets some code editing guidelines, like spacing that many people have different and standardizes it for editors that support it (most have plugins for it).  It is helpful with contributions so people don't waste time with talking about or fixing 2 spaces vs 4 spaces sort of issues.
> Adding editor config file.

- src/styles/style_manager.js
- src/styles/text/text.js
- test/fixtures/sample-remote-style.yaml
- test/fixtures/sample-scene.json
- test/style_spec.js
We want to properly support situations where multiple parent-child styles a re defined in the scene def, and then get built in proper order according to their dependencies. i.e. even when a child style appears *before* its parent:
```
styles:
child:
extends: parent
...
parent:
extends: polygons
...
```
> Properly compile styles in order of dependency

- README.md
- bower.json
[Bower](http://bower.io/) is pretty much the best option for front-end dependency/library, albeit far from perfect.
This adds a `bower.json` which works a lot like `package.json`.  It's a bit annoying to have manage both, but it's worth the ability to do: `bower install tangram`.
I already registered the `tangram` name in bower since this is not an authenticated action.
> Add bower.json

- watch.sh
To install entr on OS X, type
brew install entr
> Switch the watcher to something that can work on OS X

- src/scene.js
- test/scene_spec.js
A simple approach to pruning tiles outside a given distance from the viewport, to reduce the amount of memory retained.
> Prune tiles outside viewport

- demos/main.js
- demos/scene.yaml
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons.js
- src/styles/rule.js
- src/styles/style.js
- src/styles/style_parser.js
- test/rule_spec.js
There's no need to re-parse string-based colors, and interpolated values between zooms, for every feature in the scene (!). By caching these values (sometimes a single static value, sometimes one value-per-zoom), we can get up to 50% decrease in tile build time.
> Add caching for common style parameter parsing

- demos/scene.yaml
- src/styles/rule.js
- test/rule_spec.js
Follow standard inheritance for `order` property, so that child rules replace the order of value of parent/ancestor rules (instead of summing together).
We may revisit the order sum behavior in the future, with new syntax. But came to the conclusion that this is a simpler default.
> Simplify order inheritance

- demos/scene.yaml
- src/gl/texture.js
- src/scene.js
- src/styles/style_manager.js
- src/utils/utils.js
By making resources in the scene file (textures, shader blocks loaded via URL) relative to the scene file itself, we can load entire styles remotely/cross-origin, even when they reference other resources.
For simple local styles, this just means that you should specify any resources as relative to the location of the scene file. For example, in the bundled example, several resources that had a path of `demos/images/...` were changed to `images/...`, since the `scene.yaml` already resides inside the `demos/` directory.
> Make resources in scene file relative

- demos/main.js
- src/scene.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style.js
- src/styles/style_manager.js
- src/styles/style_parser.js
- src/styles/text/text.js
- src/tile.js
After switching to a system where all outlines were drawn as additional draw groups alongside the object they were outlining, we realized that the old system, where we had an explicit `outline` syntax, was really useful. In particular, it's useful for things like drawing a consistent outline width (e.g. 2px outline) on a line that is scaling between zoom levels. This PR:
- Refactors tile mesh construction so that styles can delegate to other styles (e.g. a line style can build its inner line, then calculate the appropriate outline width and call the same or another line style to build the outline geometry).
- Adds support for the `outline` parameter in the line base style.
- Simplifies the dynamic line scaling: now that base tile zoom is determined by `floor` instead of `round`, we only …
> Restore support for old `outline` style parameter (for lines)

- makefile
- package.json
- src/data_source.js
Previously we were importing the TopoJSON library with `importScripts()` via the officially hosted D3 endpoint (http://d3js.org/topojson.v1.min.js), but it turns out that doesn't support HTTPS. So, we've opted to just include the library directly, at the cost of 6k minified, but no external network dependency.
> Include the TopoJSON decoder directly in the library

- src/scene.js
- src/styles/style_parser.js
- src/tile.js
Add a simple tile LOD factor, that can be used to load lower-zoom-level (and also lower-detail) tiles. Currently no simplification is applied by default, leading to no visible changes. In the future, could be used in conjunction with different LOD tiles server-side to try different tile size/detail mixes, similar to Mapbox's "over-zoom" concept.
> Simple tile level-of-detail factor

- demos/main.js
- src/data_source.js
This is mostly a proof of concept.  Feel free to close after checking it out.
This just adds the ability to add an `alter_data` function to a data source that will be run before the data gets projected and rendered.
It's currently only for GeoJSON Tile layers since its not necessarily the best way to do this.
> Adding basic mechanism for altering tile data.

- src/data_source.js
- src/scene.js
- src/scene_worker.js
- src/styles/style_parser.js
- src/tile.js
- src/tile_manager.js
- test/data_source_spec.js
- test/scene_spec.js
- test/tile_manager_spec.js
- test/tile_spec.js
Revamps how multiple data sources are handled.
Previously: all sources were combined into a single tile object. This didn't allow sources with differing maximum zooms to mix well (all sources were artificially limited to the lowest source max zoom). It also wasn't possible to apply different styles to a source past its max zoom (since it was only built once at the max zoom and then that tile displayed at higher zooms).
Now: internally, tiles are built per source per view zoom, which means that sources can be mixed more easily, and style rules can be applied past the max zoom (separate tile VBOs are built for the higher zooms). This also opens the door to selectively rebuild tiles by source, which will be useful for more dynamic sources (see the road filtering demo for an example).
> Build a tile per source per view zoom

- src/leaflet_layer.js
- src/module.js
- src/scene.js
- src/scene_worker.js
- src/selection.js
- src/utils/utils.js
- test/helpers.js
- test/leaflet_layer_spec.js
- test/scene_spec.js
- test/tile_manager_spec.js
- test/tile_spec.js
Previously, if the scene failed to load a config file, it would end up in an un-initialized state that it was usually not able to recover from.
Now, it is reliable to call `Scene.load(config)` multiple times, including when previous calls failed. In addition, if a config fails to load, but there is a previously valid config available, the scene will revert to the previous valid configuration (think of cases like an interactive editor where several config states may be loaded in succession, some valid and some not).
> Recover from failed scene config loads

- demos/scene.yaml
- src/styles/text/text.js
Adds the ability to specify label priority in draw rules in the scene file. This is done through the `priority` field. For example, to set different priorities on `places` vs. `landuse_labels` layers:
```
places:
data: { source: osm }
draw:
text:
priority: 1
font:
typeface: italic 11pt Helvetica
fill: black
landuse_labels:
data: { source: osm }
draw:
text:
priority: 2
font:
typeface: Italic 10pt Lucida Grande
fill: darkgreen
```
@sensescape @nvkelso @meetar:
Currently, **lower** priority values take precedence over higher ones. So `priority: 1` labels will be drawn before `priority: 2` labels. In English, I usually think of something that is "priority one" as being more important than something that is "priority two". On the other hand, "high priority" could also imply a higher number :) …
> Label priority

- src/styles/builders.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons.js
- src/styles/polygons/polygons_vertex.glsl
- src/styles/text/text.js
- src/utils/utils.js
Packs some vertex attributes into smaller data types:
- position: floats -> signed shorts
- normal: floats -> signed bytes
- texture UVs: floats -> unsigned shorts
- line extrusion: floats -> signed shorts
- layer order: floats -> signed shorts
This produces about a 44% decrease in memory usage for VBOs in a typical complex scene (midtown Manhattan zoom 15).
> Pack vertex attributes

- src/scene.js
In some cases, it may be desirable to let labels, icons, or other items drawn with full alpha blending be occluded by other objects, such as buildings.
This branch adds a blending mode for that, called `inlay` (as opposed to `overlay`). The inlay blend has depth test on, but depth write off. This means that the inlay geometry is appropriately depth-positioned with regard to any previously drawn geometry, but will not guarantee correct depth between other geometry drawn with the inlay mode (e.g., multiple inlay geometries will overlay each other).
> Inlay blending mode

- demos/scene.yaml
- src/gl/extensions.js
- src/gl/shader_program.js
- src/module.js
- src/styles/style.js
- src/styles/style_manager.js
Custom styles can now enable GL extensions, with a new `extensions` property (within `shaders`). For example, a style that uses the `OES_standard_derivatives` extension:
```
grid:
base: polygons
lighting: false
shaders:
extensions: OES_standard_derivatives
blocks:
color: |
// From: http://madebyevan.com/shaders/grid/
// Pick a coordinate to visualize in a grid
vec3 coord = v_world_position.xyz / 10.;
// Compute anti-aliased world-space grid lines
vec3 grid = abs(fract(coord - 0.5) - 0.5) / fwidth(coord);
float line = min(min(grid.x, grid.y), grid.z);
// Just visualize the grid lines directly
color = vec4(vec3(1.0 - min(line, 1.0)), 1.0);
```
`extensions` is either a single extension name, or a list of one or more requested extensions, e.g. for multiple extensions:
` extensions: …
> Styles can enable GL extensions

- src/tile.js
Allow scene layers to specify more than one layer to pull from the data source. The data from all layers is combined into one layer on the Tangram side.
Example applying the same label styling to `pois` and `buildings` layers in the data source:
```
layers:
labels:
data: { source: osm, layers: [pois, buildings] }
filter: ...
draw: ...
```
> Multiple datasource layers

- src/styles/points/points.js
It turns out a common use case for sprites is to dynamically match the sprite name to a feature property. For example, many of our `kind` property values for POIs directly map to names of sprites in our texture. We can write a rule to match these:
```
draw:
icons:
sprite: function() { return feature.kind }
```
But! While that can eliminate hundreds or thousands of lines of style rules with this one rule, there are still times when we won't have a sprite for every possible feature `kind` value. This PR addresses that by adding a `sprite_default` property. When set, this property is used as the sprite value in cases where the value of `sprite` isn't found in the texture.
For example, we can make all sprites default to a generic icon, and only apply that rule at higher zooms, like this:
``` …
```
> Add a `sprite_default` draw parameter to points

- src/geo.js
- src/sources/data_source.js
- src/sources/geojson.js
While many GeoJSON/TopoJSON data sources (including Mapzen's tiles) are encoded with typical CCW-ordered outer rings (and CW inner rings), it turns out not all data sources follow this, and GeoJSON does not enforce it. In particular, user-supplied GeoJSON/TopoJSON files may have inverse ring orders depending on how/where they were generated.
To fix this, we can enforce CCW winding order. This PR adds an option to do that per-data-source. By default, **tiled** data sources do **not** enforce winding order (i.e. they are assumed to already be correctly wound); **non-tiled** data sources **do** enforce winding order (i.e. they are assumed to not be safe). (Defaulting off saves a bit of needless computation.)
These defaults can be overridden if desired, for example to reverse these options: …
> Optionally enforce polygon winding order

- src/styles/points/points_fragment.glsl
- src/styles/text/text.js
Fixes the "dirty" halos on text seen in #179 (see for more detail).
This was an issue with pre-multiplied alpha handling between WebGL and Canvas. It looks like the text rasterized into the canvas uses pre-multiplied alpha, which means that instead of the halo simply alpha-fading to 0 at is edges, it is also "fading" out the halo RGB itself. For example, with a yellow halo, you get a dirty gray at the edge as the RG components interpolate from 1 to 0 (instead of remaining constant while just the alpha interpolates).
Our WebGL blending pipeline is currently setup to expect un-premultiplied alpha. To fix this for now, we are simply dividing the color RGB by its alpha in the shader to "un-multiply" the alpha
In the future, we may consider adding a new blending mode, alongside overlay, that …
> Un-multiply alpha on text styles

- demos/scene.yaml
- src/tile.js
We support pulling multiple data source layers into a single style layer, like this:
`data: { source: osm, layer: [places, pois] }` 
However, there has been no way to distinguish *which* layer each feature came from, when filtering or dynamically computing properties for these features.
This PR adds a `$layer` property that contains this information. For the example above, `$layer` would be `pois` for features from the `pois` layer.
> Add $layer for filtering features according to their source layer

- src/gl/shader_program.js
- src/material.js
- src/styles/style.js
- src/styles/style_manager.js
We recently added shader error events with detailed metadata, allowing Tangram Play to extract information about which styles shader blocks failed to compile, including specific line numbers mapped from GL shader compile errors. However, after using this in the editor, it became clear that the need was more complex than the original implementation. For example, Tangram itself injects `global` shader blocks internally, for common shared functions, throwing off the line numbers for user-defined shader code. Additionally, compile errors in a block that was mixed in from a 'parent' style wouldn't be found when the 'child' style failed to compile, preventing the error from being properly syntax highlighted.
This PR adds lower-level tracking of where each shader block came from. For example, …
> Track shader block 'scope'

- src/styles/text/text.js
Adds the ability for the label `priority` parameter to be dynamic, either:
- Tied to a feature property, by setting `priority` to a string value with the property name, e.g.
- `priority: label_priority`
- Computed from a JS function, e.g.
- `priority: function() { return Math.floor(feature.area / 1000); }`
Requested by @nvkelso for upcoming tile data for label priorities.
> Dynamic label priority

- demos/scene.yaml
- src/styles/text/feature_label.js
- src/styles/text/text.js
Split single `typeface` property into individual properties that match Tangram ES syntax:
- `family`: Helvetica, Futura, eta.
- `size`: in pt, px, or em
- `style`: e.g. italic
- `weight`: e.g. bold
- `transform`: capitalize, uppercase, lowercase
Keeps legacy support for `typeface`, will be deprecated.
> Update font properties to match ES

- demos/scene.yaml
- demos/transit.yaml
- src/gl/glsl.js
- src/scene.js
- src/scene_loader.js
- src/styles/style_manager.js
- test/fixtures/sample-scene.json
- test/fixtures/sample-scene.yaml
- test/helpers.js
- test/leaflet_layer_spec.js
- test/scene_spec.js
- test/style_spec.js
This branch has all the functionality for scenes to `include` other scenes -- the scene objects get merged together before they are evaluated, enabling composition such as:
- Splitting a large scene into several files (one for roads, one for POIs, etc.)
- Pulling in an existing basemap (e.g. a Mapzen-hosted design) and then adding your own data/layers on top
- Remixing an existing design by pulling it in and then adding/overriding rules to tweak the style
- Possibly replacing the ability to load remote styles, by using `include` as an alternative (though style loading via URL also has some other namespace benefits currently)
However! This PR has the `include` functionality itself disabled. I would like to pull in related refactoring in this branch (including making it easier for Tangram …
> Preparation for scene `include` functionality

- package.json
- src/styles/text/text.js
- src/utils/utils.js
Canvas text in Safari appears to NOT be premultiplied, unlike in Chrome and FF.
See https://github.com/tangrams/tangram/issues/179 for background.
> Adjust for Safari Canvas alpha

- src/scene_worker.js
This makes it much easier to track down problems with `eval`ed functions from the scene file.
> Include text of style evalutation error in debug log

- src/leaflet_layer.js
- src/utils/utils.js
Further modifications to Leaflet mouse-wheel scrolling and zoom behavior. Fixes an apparent recent regression in Chrome, where some interaction between Tangram, Leaflet, Chrome requestAnimationFrame (and CodeMirror in the case of Tangram Play) was causing a sync lock, making mouse wheel scroll lock up for animated styles (no scroll would occur until the wheel was stopped moving, then it would move either a very small amount, or a big jump). This seemed related to Leaflet's debounce processing the scroll wheel input. This PR disables that. (These modifications can be disabled with the `modifyScrollWheel: false` option if they cause conflicts with other client app expectations or a need for default Leaflet scroll wheel behavior.)
> Leaflet zoom/scroll wheel adjustment

- src/styles/builders.js
- src/styles/lines/lines.js
- src/styles/polygons/polygons.js
When constructing polylines, we exclude line segments that coincide with tile boundaries by default (they can be enabled if desired with the `tile_edges: true` style parameter, usually for debugging).
We have not been applying the same logic to polygon extrusion, most likely an oversight. We haven't noticed because Mapzen vector tile building polygons are unclipped, and these are the most common extrusion case. A recent issue reported by a user revealed this problem when using non-tiled GeoJSON.
This extends the same behavior (and `tile_edges` flag) to the `polygons` style.
> Don't extrude polygon edges along tile boundaries by default

- package.json
- src/styles/text/text.js
- src/utils/utils.js
Fixes the last known issue with dirty text halos (!). It turns out that Canvas alpha appears to be premultiplied on OS X Safari, but is NOT on iOS Safari. This led to previous confusion on my part because those two are usually in sync. This PR fixes the dirty text by excluding iOS from the alpha unmultiply step for text rendering.
See #192, #180, #179 for further background.
> Don't un-multiply Canvas alpha on iOS

- demos/css/main.css
- demos/main.js
- package.json
- src/gl/render_state.js
- src/leaflet_layer.js
- src/scene.js
- src/styles/style_parser.js
- src/styles/text/text.js
- src/utils/utils.js
- test/leaflet_layer_spec.js
Adds alpha to the Tangram GL canvas, which allows for Leaflet layers (or other HTML content) to be placed *beneath* the map, in addition to on top of it. The GL canvas is now inserted in the correct location in the Leaflet DOM (previously it was pulled out of the DOM to make positioning simpler, and because without alpha it often got covered by other layers). 
This also necessitates a few changes to client interactivity handling, since we want listeners and pop-ups attached to the map container, not the Tangram scene container. (see https://github.com/tangrams/tangram/compare/alpha-background#diff-a2925ce738063617bef38726407de2d0R484, https://github.com/tangrams/tangram/compare/alpha-background#diff-a2925ce738063617bef38726407de2d0R511); cc @meetar and @nvkelso on this point for adjusting …
> Alpha background

- src/styles/text/feature_label.js
- src/styles/text/text.js
Re-implements multi-line labels (previous implementation had issues and was disabled). Labels with word wrap / line breaks are now drawn directly as multi-line labels in the Canvas texture (e.g. the word wrapping is implemented as part of the Canvas text drawing, vs. as part of the Tangram label/geometry building/rendering process).
The maximum number of characters per line before a line break occurs is configurable via the `max_line_width` parameter (should this be `max_line_characters`?). 
```
draw:
text:
max_line_width: 10
...
```
Word wrap is **enabled** by default for point labels (labels for point or polygon geometries) with a default `max_line_width` of **15 characters** (is this the best default?), and is **disabled** by default for line labels. Word wrap can be explicitly …
> Multi-line labels

- demos/scene.yaml
- src/styles/text/feature_label.js
- src/styles/text/label.js
- src/styles/text/label_line.js
- src/styles/text/label_options.js
- src/styles/text/label_point.js
- src/styles/text/text.js
- test/labels_spec.js
Add a `placement` property for point labels, to place them in a cardinal direction anchored to their point position (default positioning is centered on anchor point).
Example:
```
draw:
text:
placement: E
offset: [12px, 0px]
font:
...
```
Valid `placement` values are: `N`, `S`, `W`, `E`. Note these are actually interpreted as relative up/down/left/right placements relative to the anchor, not actually moving the label in the specified direction on the map. If this is undesirable we can also use an alternative like: `up`, `down`, `left`, `right`.
Also still thinking about support for:
- Dynamically determining `placement` from a feature property and/or JS function
- Supporting multiple placement options, to try in order of priority, e.g. `placement: [E, S]`
> Add cardinal direction placements for point labels

- src/styles/style_manager.js
This fixes an issue where uniform values set at run-time would not inherit to "descendant" styles they were mixed into. This was because uniform values were cloned (along with the rest of the style properties) at mixing time. The "parent" and "child" uniforms ended up as separate JS properties, even if they were intended to have the same value (e.g. the child style did not override the uniform with a new default value). Usually this is not noticeable, but in situations where uniforms are dynamically altered at run-time (such as demos with GUIs), the values would not propagate and the parent and child would diverge. @patriciogonzalezvivo noticed this when working on small "modules" of common style functionality.
This PR fixes the behavior by creating JS getters and setters for uniforms. …
> Uniform run-time values forward from ancestor to descendant

- makefile
- package.json
- src/leaflet_layer.js
- src/module.js
- test/leaflet_layer_spec.js
Now, you can bundle up all of your app's front-end dependencies via Browserify except for Tangram. Tangram will wait until `Tangram.leafletLayer()` is called before looking for Leaflet.
In HTML:
```html
<script src='./path/to/tangram.min.js'></script>
<script src='/js/bundle.js'></script>
```
In your `bundle.js`:
```js
var L = require('leaflet')
// Your other required dependencies
// [Init Leaflet map...]
// Add Tangram scene layer
// Provide the required Leaflet variable to Tangram
var layer = Tangram.leafletLayer({
leaflet: L,
scene: 'https://raw.githubusercontent.com/tangrams/refill/gh-pages/refill.yaml',
}).addTo(map);
```
- An entry point for `dist/tangram.min.js` is provided in `package.json` in case the repository is downloaded as an NPM module.
- When building the module, the …
> Tangram can be loaded outside of a bundled JS

- src/gl/shaders/accessors.glsl
- src/scene.js
- src/styles/points/points_fragment.glsl
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons_fragment.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style_manager.js
Adds `vec3 worldNormal()` accessor, to match ES behavior from https://github.com/tangrams/tangram-es/pull/375.
Adds inverse normal matrix (`u_inverseNormalMatrix`), and `TANGRAM_EPSILON` for floating point comparisons (to match ES).
> World normal accessor

- demos/scene.yaml
- src/styles/points/point_anchor.js
- src/styles/points/points.js
- src/styles/text/feature_label.js
- src/styles/text/label_point.js
Generalizes the logic from point labels so that it also applies to points/sprites. The same `anchor` values apply (`left`, `bottom-right`, etc.). Unlike with labels, the `align` keyword is not needed.
> Support anchors for points/sprites

- demos/scene.yaml
- src/scene.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons.js
- src/styles/style.js
- src/styles/style_parser.js
- src/styles/text/canvas_text.js
- src/styles/text/feature_label.js
- src/styles/text/text.js
- src/utils/utils.js
Adds zoom-based interpolation ("stops") for the following font properties:
- Font size (specified in px, pt, or em)
- Fill color (partially worked previously, fixes bugs with using string colors)
- Stroke width (specified in px)
- Stroke color
```
draw:
text:
font:
family: Helvetica
fill: [[14, white], [18, gray]]
size: [[14, 12px], [16, 16px], [20, 24px]]
stroke:
color: [[16, white], [18, red], [20, blue]] 
width: [[14, 3px], [20, 8px]]
```
> Font property interpolation by zoom

- src/styles/rule.js
- src/styles/style_parser.js
- src/styles/text/label.js
- src/styles/text/layout_settings.js
- src/styles/text/repeat_group.js
- src/styles/text/text.js
This introduces draw parameters for controlling how often labels are allowed to repeat. Two style parameters are added to control this behavior, `repeat_distance` and `repeat_group`.
- The `repeat_distance` parameter (for `text`-based `draw` groups) that specifies **minimum distance in pixels** between labels.
- Currently, this is simply calculated as a center-to-center distance between two label bounding boxes, though it could be expanded to account for label size. For performance, possibly a simpler approximation and not a true distance between bounding boxes; the behavior here needs to adhere reasonably close to the desired style, but does not need to be pixel-perfect.
- Note that because the Tangram JS architecture processes each tile in isolation (and manages labels and their …
> Label repetition

- src/scene.js
- src/styles/style.js
- src/styles/style_manager.js
`blend_order` is an optional parameter used when defining a render style, which controls the order in which styles *with non-opaque blending (`add`, `multiply`, `inlay`, `overlay`)* are rendered. `blend_order` is an integer greater than or equal to zero.
Previously, styles were bucketed by blending type, and rendered in the following order: `opaque`, `add`, `multiply`, `inlay`, `overlay`.
With this PR, the order is now:
- All `opaque` styles render first
- All non-`opaque` styles **without** a defined `blend_order` render next, sorted by `add`, `multiply`, `inlay`, `overlay`
- All non-opaque styles **with** a defined `blend_order` render last, sorted by `blend_order` (ascending), sub-sorted by `add`, `multiply`, `inlay`, `overlay`
Each group above also now has a final sub-sort by style …
> Add `blend_order` to control render order of styles with non-opaque blending

- src/styles/rule.js
- test/rule_spec.js
Sometimes a feature matches multiple layers, at the same depth, that set the same property (or properties). This isn't desirable because it's ambiguous, and should be avoided when authoring layer rules (it *is* often useful to write multiple layers that match the same feature, they should just be used to control different properties, for example one set of rules to control color and another parallel set to control order). However, it's also a little too easy to do accidentally :)
Previously, the resolution of which layer would "win" was undefined, leading to divergent behavior between Tangram JS and ES. This PR resolves the conflict by **lexically sorting the layers by name**. As with deeper layers overwriting the properties of shallower layers, the **last layer sorted by name** will …
> Resolve ambiguous draw rules by lexical sort

- demos/main.js
- src/scene.js
- src/tile_manager.js
Incorporates screenshot-related support from the demo into Tangram itself. This will be useful for automated render testing, for apps like Tangram Play that may want to capture the view periodically, and for other users who would like to incorporate screenshot support.
API changes:
- A new scene method, `Scene.screenshot()`, which queues a screenshot request, and returns a Promise that fulfills when the screenshot is available. (The screenshot must be "queued" because it cannot be captured immediately: we must ensure that the GL buffer is finished drawing, and then must capture the buffer contents just after rendering, before it is cleared by other operations.)
- The promise resolves with an object containing two properties:
- `url`: a data URL of the Canvas contents, suitable for loading …
> Add screenshot support

- src/styles/builders.js
- src/styles/lines/lines.js
Adds back the previously lost miter limit functionality for polyline builders. The miter limit converts miter joins to bevels when the join angle is very sharp, specifically when the miter join length is longer than the ratio of the `miter_limit` to the width of the line.  See [SVG miter limit](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit) for reference.
Exposes as `miter_limit` in `lines` style, default miter limit is 3., e.g.:
```
draw:
lines:
color: red
width: 5px
miter_limit: 2
```
Examples from [Hong Kong paths](http:tangrams.github.io/eraser-map/#20/22.27658/114.21159):
**Miter limit 3 (default)**
**Miter limit 2**
**Miter limit 1.5**
> Add miter limit for line builder

- src/scene.js
Add data source **method** from JS through an interface:
```scene.setDataSource (name, config)```
**Arguments** `name` and `config` must be provide. 
Notes:
+ If ```name``` doesn't match an existing source it will create one for you
+ the ```config``` obj follow the YAML scene spec.
- ```type``` need to be provide (it's content could be: 'TopoJSON', 'GeoJSON' or 'MVT'), together with ..
- a source (```url``` or ```data```): ```url``` expect a string with or with out ```{x}```, ```{y}``` and ```{z}``` template or ```data``` expects directly a JavaScript object which will be interpreted acording to the ```type```
Examples:
```scene.setDataSource("osm", {type: 'TopoJSON', url: "//vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson" });```
```
var geojson_data = {};
... …
```
> Add data source

- src/styles/builders.js
Adjusts our tile edge filtering (which removes line segments that fall on tile edges, as they are generally not desirable to draw) so that it will filter out lines that fall on **any** tile edge, not just the edges of the "local" tile. This is done by simply modding the coordinates against the tile size.
This is useful for cases where geometry is clipped to some other tile multiple, e.g. 3-tile bbox range. See https://github.com/mapzen/vector-datasource/issues/197 for background.
Before:
After:
> Filter lines on all tile edges

- demos/scene.yaml
- src/styles/text/text.js
This adds the ability for `text_source` to be an array of possible sources of label text, in priority order. Each array element is evaluated as if it was a `text_source` value (meaning each element can be either a *string* value that specifies a feature property by name, or a *function* that returns displayable label text). The first non-null evaluated source in the array is used as the label text.
The primary use case here is to support **preferred language** for text labels. For example: 
`text_source: [name:en, name]`
This will display an English label (`name:en`) when available, and will fall back to the default local `name` when not available.
For example, here is Moscow with default `name` only, and with the English preference as specified above:
Looking to the future, once we have …
> Label text can be defined as a series of fallbacks

- src/sources/data_source.js
- src/styles/builders.js
- src/styles/polygons/polygons.js
- src/tile.js
Currently, Mapzen's own vector tiles have a CCW winding on polygon rings, which is opposite what the MVT format [currently specifies](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) (Geo/TopoJSON do not have an officially specified winding order). We plan to rectify this in an upcoming tile release (see https://github.com/mapzen/mapbox-vector-tile/pull/21), but it raised the issue that Tangram ideally ought to support data sources with either winding order, for maximum compatibility.
This PR enables that by using the order of the first polygon ring processed in each data source, to indicate the expected order of outer rings. This allows for automatic switching between CW or CCW-wound polygons on a per-data-source level, even mixing sources with different winding orders. (Note …
> Support arbitrary winding order

- src/styles/builders.js
Our previous tile edge removal logic only removed line segments that were *on* (or nearly on, within a tolerance) the tile bounds. This works for unbuffered tiles like Mapzen's, which are clipped to tile boundaries, but does not render properly for buffered tiles, such as Mapbox's.
This approach simply throws out line segments that lie outside the tile bounds (retaining the tolerance). Along with https://github.com/tangrams/tangram/pull/241, ensures proper support for Mapbox-served MVT tiles.
Before/after examples, where the "double lines" visible with the previous logic are lines at the edge of the tile buffer area (so one buffer for each adjacent tile, two lines total), which were not removed, but now are no longer rendered:
> Exclude line segments that fall outside the tile bounds

- package.json
- src/camera.js
- src/geo.js
- src/labels/collision.js
- src/leaflet_layer.js
- src/light.js
- src/module.js
- src/scene.js
- src/scene_worker.js
- src/sources/data_source.js
- src/styles/points/points_fragment.glsl
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons_fragment.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/styles/text/text.js
- src/tile.js
- src/tile_manager.js
- src/tile_pyramid.js
- src/utils/gl-matrix.js
- src/view.js
- test/scene_spec.js
- test/tile_manager_spec.js
- test/tile_spec.js
Adds "proxy tile" support: while tiles are loading, previously loaded tiles from higher or lower zooms will be shown in their place, providing more visual continuity and reducing "breaks" or "flashes" between tile zooms.
- Proxy retrieval: To speed up retrieval of proxy tiles, a new `TilePyramid` object tracks ancestor/descendant relationships across zoom levels.
- `getAncestor()` and `getDescendants()` methods recursively find available proxy tiles above or below a given tile (for descendants, the max level to descend can be set, since there is up to 4x increase in number of potential proxy tiles for each level; current max depth default is 3 zooms).
- There is special handling for over-zooming in `TilePyramid` that could be simplified, and in the future should be generalized to support …
> Proxy tiles

- package.json
- src/utils/utils.js
Builds with a tangram fork of js-yaml that only has YAML read support: https://github.com/nodeca/js-yaml/compare/master...tangrams:read-only
Reduces minified output from 509k to 426k (**-83k**), and gzipped output from 137k to 114k (**-23k**).
Closes #254.
> Build with read-only fork of jsyaml

- src/scene.js
- src/scene_worker.js
- src/utils/utils.js
- src/utils/worker_broker.js
Optimize the worker message-passing pipeline:
1. It's been found that because native browser serialization of Web Worker messages is slow, it is generally faster to stringify them before sending, and then parse on reception. See http://nolanlawson.com/2016/02/29/high-performance-web-worker-messages/ for details.
Stringifying is not an option in cases where [transferable objects](https://developer.mozilla.org/en-US/docs/Web/API/Transferable) are included in the message payload.
This PR automatically stringifies worker messages when possible, through the `WorkerBroker`. `JSON.stringify` is applied before the message is sent, and `JSON.parse` when it is received. When transferable objects are found in the payload, the message is left in its original object form.
For Tangram, this change is …
> Optimize worker message pipeline

- src/styles/builders.js
We've found several cases where tiles (either Mapzen-served or user-provided) can contain degenerate geometries, particularly lines with duplicate consecutive points (this can happen when quantizing for specific output formats, or during re-projection, etc.).
In Tangram JS, these are manifested as "fat arrowheads". This is because the line builder attempts to find an extrusion vector between two coincident points, resulting in a vector of `[NaN, NaN]`. These `NaN` values get set in the VBO as signed short ints, where they are converted to some unexpected non-zero value, sending the line careening outwards:
The complete solution is probably a combination of server-side and client-side resiliency checks. See https://github.com/mapzen/vector-datasource/issues/569 for further background. 
For …
> Remove duplicate consecutive points during line building

- demos/scene.yaml
- src/sources/data_source.js
- src/utils/utils.js
- test/data_source_spec.js
This adds the ability for data source definitions to add custom URL parameters to the query string. This has little benefit currently, since you can just write out the whole URL explicitly. But it will allow us to more easily customize parameters like API keys:
- By having the Leaflet plugin set the API key param in the scene file when it's passed through as an option
- Once we incorporate file inclusion, this will allow users to easily import a Mapzen basemap and then set their own API key.
Example:
Instead of the full URL, `http://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-HqUVidw`, you can write:
```
sources:
osm:
type: TopoJSON
url: http://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson
params:
api_key: vector-tiles-HqUVidw
```
The future inclusion example …
> Data sources can append custom URL params

- src/gl/shaders/accessors.glsl
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/tile.js
We concluded in https://github.com/tangrams/tangram/issues/259 that we should scale the `modelPosition()` accessor to account for tile overzooming, providing a consistent scale for shader-based patterns. 
This is done by adding an additional scaling factor of `2^(tile style zoom - tile coord zoom)` to the `modelPosition()`.
Implementation notes:
- `u_tile_origin.z` was already set to the tile's *style zoom* (the zoom at which the tile is being displayed) in JS, but to the *coordinate zoom* (e.g. the zoom at which the tile was loaded) in ES. We concluded that it should be set to the **style zoom** on both platforms.
- However we also need access to the tile coordinate zoom, which is now provided as `u_tile_origin.w`.
- Previously, JS was using `u_tile_origin.w` as the depth offset for …
> Scale modelPosition() to account for tile overzooming

- src/styles/polygons/polygons_fragment.glsl
- src/styles/polygons/polygons_vertex.glsl
This is yet another revision of shader block application, after the v0.6.0 changes revealed compatibility issues with existing styles and limitations on procedurally generated textures and custom lighting setups.
With this new logic, the `color` and `normal` blocks are always injected, regardless of the `lighting` mode:
- `lighting: fragment`:
- `normal` and `color` blocks executed in the fragment shader.
- `lighting: vertex`:
- `normal` block is executed in the vertex shader
- Lighting intensity (e.g. lighting if applied to a pure white surface) is calculated in the vertex shader, and interpolated in the fragment shader.
- `color` block is executed in the fragment shader, and the result is multiplied by the interpolated lighting intensity. This allows for `color` to create procedural …
> Revise lighting blocks: always include `color` and `normal`

- src/selection.js
- src/styles/style.js
- src/tile.js
This adds the fully qualified names of the `layers` that matched a feature to the selection object returned for it, as `feature.layers`. For example:
```
scene.getFeatureAt(pixel).then(function(selection) {
if (selection.feature) {
console.log(selection.feature.layers);
}
});
=> ["roads:major_road:trunk_primary:early", 
"roads:major_road:trunk_primary:routes:early", 
"roads:major_road:trunk_primary:labels-trunk_primary-z13"]
> Add matching layers to feature selection info

- src/labels/label_line.js
- src/styles/text/text.js
- src/tile.js
We've found that our line labelling logic is insufficient for overzoomed tiles, because it only places one label per line, which often provides enough density at each tile's "native" zoom, but is too sparse (sometimes dramatically so) when tiles are overzoomed multiple levels. See #273.
This PR increases line label density by attempting to place multiple labels per line. For each line, up to `2^dz` tiles are placed, where `dz` is the number of levels of overzooming being applied. For example, a z16 tile would still place 1 (2^0) label at z16, but when displayed at z18 the same line would place up to 4 (2^2) labels. This is done with a "coarse subdivide", splitting the line by segment. Each label placement is assigned a range of segments in which it can place.
Examples with and without …
> Subdivide line labels by segment on overzoomed tiles

- src/scene_loader.js
- src/scene_worker.js
- src/styles/rule.js
- src/styles/style_parser.js
- src/tile.js
This PR adds a concept of **global properties**, which are user-defined properties in the scene file that can be substituted for values elsewhere in the file. This is useful for values that are referenced in multiple places in the scene file, and would benefit from a centralized definition for easier editing. Examples include common colors, language preferences, or visibility flags used to tweak styles.
Global properties are scoped as everything under the top-level `global` block of the scene file, including nested properties:
```
global:
labels: true # label visibility flag
language: name:en # preferred language for label display
colors: # group common colors together
color1: red
color2: green
color3: blue
```
These properties can then be substituted elsewhere in the scene file with …
> Global property substitution

- demos/main.js
- src/leaflet_layer.js
- src/scene.js
This PR simplifies the process of setting up Tangram feature selection callbacks (such as on hover or click), removing the need for boilerplate code for DOM events by tying into Leaflet's existing event handlers.
A new concept of *selection event handlers* has been added to Tangram, currently with two events supported:
- `hover`
- `click`
Selection event handlers will be passed the same `selection` object returned by direct calls to `scene.getFeatureAt()` (which is still supported and available for custom input/event needs).
Two additional properties have also been added to the returned `selection` object:
- `pixel`: the XY location within the map container where the event occurred, in the form `{ x, y }` (this wasn't previously necessary since the user already needed to pass it …
> Selection event handlers

- src/gl/render_state.js
- src/scene.js
#260 
Consistent behavior between -es and -js with several styles including while using alpha blending on. 
No specific improvement on render time noticed nor overdrawing improvements, profiled on mobile and browser.
> Use GL_LESS for depth func

- src/module.js
- src/styles/text/canvas_text.js
- src/styles/text/text_settings.js
A few optimizations to Canvas text rendering:
- Cache results of unique style/text string combinations, so we can avoid computing them more than once.
- This typically leads to anywhere between 40%-60% cache hit rate, reducing potentially expensive Canvas text `measureText()` calls (especially observed as slow for non-Latin characters) by about half.
- Keep the computed text lines (from applying word-wrapping) on the main thread (they don't need to be sent to the worker because they can be retrieved later during the text rasterization call).
- Only set the Canvas context text style once per text group.
> Cache Canvas text sizes and line layouts

- src/geo.js
- src/sources/geojson.js
- src/sources/topojson.js
- src/styles/points/points.js
- src/styles/text/text.js
This PR is a fix for #243 
It defines a new feature in the GeoJSON pipeline to calculate the centroids of polygons for labeling so that when the polygon is tiled, multiple redundant labels are not calculated for each tile.
In the photo above, the centroid labels are in blue, and the tiled labels are in yellow. We only want the centroid labels to appear. The expectation is for the user to not draw the text for the polygons in the data-source, but to filter the data based on points with the property `label_centroid` (this name can easily be changed) and to draw labels for only those points instead. Resulting in a rendering like the one below
This PR also supports MultiPolygons (creating a label for each one at its centroid), but doesn't currently support nested polygons (to create …
> Add support for GeoJSON polygon centroid labeling

- src/leaflet_layer.js
- src/scene.js
- src/scene_worker.js
- src/styles/style.js
By default, feature selection is only available for features where it is has been explicitly enabled via the `interactive` flag. For authoring environments like Tangram Play, or debugging, it's useful to have feature interactivity enabled for **all** features in the scene.
This PR introduces an 'introspection' mode for this purpose. When enabled, feature selection is on for all features, regardless of their `interactive` setting in the scene file.
Introspection is off by default, but can be enabled when the Tangram Leaflet layer is initialized with:
```
layer = Tangram.leafletLayer({
scene: '...',
introspection: true,
...
};
```
Or enabled at run-time with:
`scene.setIntrospection(true);`
Enabling or disabling introspection at run-time will cause the scene to rebuild automatically to …
> Add 'introspection' mode to enable interactivity for all features

- src/styles/lines/lines.js
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style_parser.js
- src/tile.js
Line width is stored in a signed short GL attribute. Previously, the units used were the tile's coordinates, which (in Tangram JS) have a scale of 0-4096. When tiles are overzoomed, those units cover more and more screenspace. This causes precision loss and eventually lines disappear entirely, as their width collapses to zero. In Bubble Wrap, for example, this causes 1px building outlines to disappear at z20 (when overzoomed from z16 tiles). See #267 for more info.
This PR adjust the units for line width to multiply by the number of overzoom levels squared, e.g. units for z16 tiles shown at z20 are multipled by 4^2, or 16x. This ensures that the same level of precision is maintained for line widths at all zooms, regardless of overzooming.
Verified this in Differ, and added a z20 test case …
> Increase line width precision for overzoomed tiles

- demos/scene.yaml
- src/builders/polylines.js
- src/gl/texture.js
- src/styles/lines/dasharray.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/points/points_fragment.glsl
- src/styles/polygons/polygons.js
- src/styles/polygons/polygons_fragment.glsl
- src/styles/style_manager.js
This PR adds support for textured lines, with additional support for line dash patterns built in (using syntax similar to SVG/Canvas-style "dash array"). This is commonly used for features such as paths, administrative boundaries, stairs, or railway lines.
**Dash Patterns**
The simplest (and likely most common way) to create line patterns is through a dash pattern. This is done with a new `dash` parameter, as part of a style definition.
- The syntax of `dash` is an array defining a pattern of alternating dashes and spaces, e.g. `[2, 1]` creates a pattern of dashes that are each 2 units long, separated by spaces that are 1 unit long.
- The unit of the dash pattern is the *width* of its line, e.g. a value of `[1, 1]` creates a series of square dashes (separated by square spaces).
- If the …
> Add textured lines w/support for dash array patterns

- src/scene.js
- src/scene_worker.js
- src/sources/geojson.js
- src/sources/mvt.js
- src/styles/rule.js
- src/utils/utils.js
- src/utils/worker_broker.js
- test/rule_spec.js
This PR optimizes a few pieces of the feature/geometry build process, namely:
- "Simple" key/value filter conditions (for both feature properties, and `$`-style context properties like `$zoom`) are pulled out and given separate, optimized treatment. This includes matches on single or multiple values, e.g. `kind: rail`, or `landuse: [residential, commercial, industrial]`.
- These matches are put into a simplified data structure, and are matched on in "native" JS, rather than in the dynamically compiled JS filters. (As with similar optimizations for zoom matching, these conditions are removed from the filter before it is compiled.) Property matches happen *after* zoom conditions (if any), but *before* remaining dynamic JS filter (if any).
- See …
> Optimize feature filters and config sync

- demos/scene.yaml
- index.html
- package.json
- src/module.js
- src/scene.js
- src/scene_loader.js
- src/styles/text/canvas_text.js
- src/utils/thread.js
Adds supports for custom web fonts, either loaded directly by Tangram, or via an external CSS stylesheet.
- The scene file has a new optional, top-level `fonts` block, which is a mapping of **font definitions**.
- The *key* of each font definition is the font **family** name, and the *value* is one or more **font face definitions** (a single object, or an array of objects).
- Each **font face definition** is an object with the following possible parameters:
- `weight`: defaults to `normal`, may also be `bold` or a numeric font weight, e.g. `500`
- `style`: defaults to `normal`, may also be `italic`
- `url`: the URL to load the font from. For maximum browser compatibility, fonts should be either `ttf`, `otf`, or `woff` (`woff2` is [currently supported](http://caniuse.com/#search=woff2) in …
> Add support for custom fonts

- demos/scene.yaml
- src/labels/collision.js
- src/labels/label.js
- src/labels/label_line.js
- src/labels/label_point.js
- src/labels/point_anchor.js
- src/styles/points/point_anchor.js
- src/styles/points/points.js
- src/styles/text/canvas_text.js
- src/styles/text/text.js
- src/styles/text/text_labels.js
- src/styles/text/text_settings.js
Support for specifying multiple `anchor` values on point labels. This is to go with similar upcoming functionality in ES: https://github.com/tangrams/tangram-es/pull/806. Completes #344.
During label placement, each anchor position is tried in the order provided. This substantially improves the density of placed labels.
Example:
```
draw:
points:
...
text:
anchor: [bottom, right, left, top]
...
```
Live preview (thanks to precog!):
https://precog.mapzen.com/tangrams/tangram/multi-anchor/#35.667086218359884,139.75703186094174,17.39925782629959
Before/after:
Note that while this does work for standalone `text`, it's likely more useful for `text` attached to `points`, such as a POI icon/text pair.
> Multiple anchor placements for point labels

- package.json
- src/module.js
- src/scene.js
- src/scene_bundle.js
- src/scene_loader.js
- src/styles/text/canvas_text.js
- src/styles/text/font_manager.js
- src/utils/resource_bundle.js
- src/utils/utils.js
This PR adds the ability to load scene "bundles" from zip files. Any relative resources (imported scene files, images, fonts) are read from within the zip bundle.
The purpose of this feature is to improve distribution and management of complex scenes, particularly by allowing users to distribute a single self-contained file with images and/or fonts.
**Scene Bundles**
A new `SceneBundle` class provides an interface for loading scene files. Given a scene URL to load, the scene bundle object loads that file, and resolves relative resources for any files loaded within the bundle. For "standard" scene YAML files (e.g. not zip bundles), this continues to work as prior scene loading has. The bundle stores a root URL for the scene, and prepends this root to any relative paths. If a resource has a …
> Add ability to load scenes from zip files

- README.md
This service is shutting down and recommending people use Mapzen's hosted one
> Remove link to OSM US hosted vector tiles

- package.json
Which now supports CSS Color Level 4 (a fancy way of saying "support `rebeccapurple`), closing the gap on full compatibility for color parsing between Tangram Play and Tangram.js. (See https://github.com/tangrams/tangram-play/issues/519)
> upgrade csscolorparser@1.0.3

- src/scene.js
- src/sources/data_source.js
- src/tile_manager.js
This adds the ability for data sources to control when tiles are requested and displayed, with three new parameters:
- `min_display_zoom`: tiles will not be requested or displayed *below* this zoom
- `max_display_zoom`: tiles will not be requested or displayed *above* this zoom
- `bounds`: tiles will not be requested or displayed *outside* of this bounding box, specified as latitude/longitude in `[w, s, e, n]` format.
I think the behavior is straightforward and the primary discussion to be had here is around the **terminology**:
- Because of our existing `max_zoom` parameter, which controls overzooming (tiles will not be requested above this zoom, but they *will* be displayed, with tile geometry scaled up), I added a `display` qualifier in these parameter names. We could consider other …
> Data sources can specify min/max display zooms and bounding box

- src/styles/text/canvas_text.js
- src/styles/text/text_settings.js
Allows for a `max_lines` parameter for text fields to truncate excessively tall labels. The current default is 5 lines. This would require documentation if implemented.
> Tall labels

- src/sources/data_source.js
Allow for tiled data sources to specify `tms` to flip tile URL y coordinate. See #359 for more info and test links.
> Support TMS-style tiled data sources

- demos/scene.yaml
- package.json
- src/styles/layer.js
- src/styles/style_parser.js
- src/tile.js
This adds an option to filter feature properties by **zoom-independent screen area**, that is, by the number of square pixels they cover.
This is done through a new `px2` unit type that can be applied to range filters, e.g.:
`filter: { area: { min: 500px2 } }`
This example filters the feature's `area` property by the number of *square mercator meters* that cover a *500 pixel screen area* at the current zoom level. This means that the `area` property must be in *square mercator meters*, as the property provided by Mapzen vector tiles is.
As with other pixel-based values in the scene file, the `px2` units are expressed in *logical pixels* (or "CSS pixels"), meaning they are interpreted at a pixel density of 1, and are automatically scaled up for higher density displays.
This syntax can be …
> Add ability to filter by screen area

- src/styles/lines/dasharray.js
- src/styles/lines/lines.js
See #355 for details.
The pattern "resolution" is 20 pixels, which should work well enough for common patterns because it's divisible by 2, 4, and 5, while avoiding making the pattern texture too big. We can adjust if needed based on usage.
cc @karimnaaji
> Allow fractional width dashed line patterns

- demos/main.js
- src/scene.js
- src/utils/media_capture.js
It turns out there is a surprisingly complete set of new [MediaRecorder APIs](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) that allow you to [capture the contents of a Canvas element](https://hacks.mozilla.org/2016/04/record-almost-everything-in-the-browser-with-mediarecorder/) to a video stream. 
This PR adds new `Scene.startVideoCapture()` and `Scene.stopVideoCapture()` methods for capturing a WebM-encoded movie of a Tangram map.
`stopVideoCapture()` returns a promise that will resolve with `url` and `blob` properties, similar to the existing `Scene.screenshot()` API. In addition, a new `type` property is now returned with both screenshot and video promises, indicating the file type. Currently the `type` is always `png` for screenshots, and `webm` for videos.
This PR …
> Add video capture methods

- src/scene.js
- src/scene_loader.js
- src/view.js
As pointed out in #390, `global` properties were being substituted **once**, when the scene loads, but were not updating with changes on subsequent updates to the `scene.config` object. This is both inconsistent with other property updates to `scene.config`, and limits some important use cases, like run-time toggles (turn transit layer on/off, turn building extrusion on/off, etc.).
This branch re-applies global property substitution when `Scene.updateConfig()` is called. This includes:
- Saving "links" between global properties and the places that they are substituted.
- Finding new references to global properties that may have been added since the last update, and adding them to the list of links.
Tangram ES recently added this functionality as well, in …
> Re-apply global property substitution

- src/labels/label_point.js
- src/styles/points/points.js
- src/styles/text/text_labels.js
- test/labels_spec.js
This removes the `move_into_tile` parameter in the scene file. The behavior that it controlled is now fixed instead of user-defined. `PointLabels` have `move_into_tile` as `false` and `LineLabels` have `move_into_tile` as true.
> Remove move_into_tile parameter for PointLabel and LineLabel

- src/styles/text/canvas_text.js
Resolves the issues brought up in https://github.com/tangrams/tangram/pull/425
Our unicode range strings to detect RTL text were being converted to their textual equivalents upon bundling. This caused some very bizarre errors, such as the appearance of unicode characters such as ﷽ in our source, in addition to much of our source code being _backwards_. 
The fix is to create the RegEx directly, instead of building it out of these strings that will get corrupted upon bundling. Thanks to @batje for spotting this!
> Compiled code no longer backwards

- src/labels/label_point.js
- src/styles/points/points.js
- src/styles/text/text_labels.js
Re-implement `move-into-tile` logic, but with `point` labels set to `move-into-tile = false`. This allows for text labels to be shifted into a tile to preserve features like neighborhoods, that aren't fixed to a particular geo location.
> Revert move-into-tile functionality

- package.json
- src/labels/intersect.js
- src/labels/label.js
Here's a fun one: reviewing our dependencies to reduce library size, I tried replacing our [`box-intersect`](https://github.com/mikolalysenko/box-intersect) module with a simple homegrown box intersection function:
The simple version not only produces a **6k smaller** minified/gzipped bundle, it's also **25% faster** on a complex label scene (Bubble Wrap central London z17).
It's possible a fancier implementation will be more performant when we have more complex collisions (such as pooling all tile labels and colliding in screen-space), so we can revisit at that time. Until then, score another one for the Dumbest Thing Possible.
> Use simple box intersection function for collision

- src/labels/point_placement.js
- src/styles/points/points.js
#409 improved placement of points-on-lines -- for symbols like road shields and one-way arrows -- by adding placement strategies on line segment *midpoints* (`placement: midpoint`), or *evenly spaced* along the line (`placement: spaced`).
For road shield placement, we are using `placement: midpoint` to keep shields as far away from line vertices as possible. This is because shields placed at vertices are more likely to be ambiguous, such as where two highways intersect.
The code from #409 places no restrictions on the *length* of the line segment on which it places a point, so a shield (or other icon) may be placed on a line segment much shorter than itself (the icon may entirely cover the line segment). This appears problematic for shields because highway interchanges are more likely to …
> Control point placement by line length ratio

- src/scene.js
- src/styles/lines/lines.js
- src/styles/style.js
- src/styles/style_manager.js
- src/tile_manager.js
- test/scene_spec.js
- test/style_spec.js
- test/tile_manager_spec.js
Compile style shader programs on-demand, the first time they are encountered in a renderable tile.
Previously, all styles referenced by a layer were compiled at scene load time.
> Compile shaders lazily

- src/leaflet_layer.js
- src/scene.js
- src/styles/points/points.js
- src/styles/points/points_fragment.glsl
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons_fragment.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/styles/text/canvas_text.js
- src/tile.js
- src/utils/debug_settings.js
- src/view.js
It was recently pointed out, in #453, that some of our label text is undesirably blurry, and further investigation showed that this is because labels are often not aligned to the screen's pixel grid.
This PR addresses this in two ways:
- When text is drawn to a Canvas, it should be aligned to the Canvas's pixel grid. Line heights and string widths from the context `measureText()` function (which can return fractional values) now have a ceiling applied.
- When text labels are positioned on screen (model, view, etc. matrices are applied), the text will often not be screen-aligned. These are now "snapped" to the pixel grid, inside the vertex shader. Snapping continuously can cause a distracting jitter effect, especially during panning. To ameliorate this, the snapping is:
- Not applied when …
> Improve text clarity by aligning sprites to pixel grid

- src/gl/shader_program.js
- src/scene.js
- test/style_spec.js
Some Tangram `styles` can result in the same underlying shader source code, for example if the only differences between them are `blend`, `blend_order`, `texture`, `dash`, or uniform values (with the same uniform names/types). This PR reuses the underlying GL shader and program objects with identical source code, to avoid unnecessarily instantiating and compiling identical ones.
> Reuse GL shader and program objects with identical source code

- src/builders/polylines.js
This code processes a polyline from its first non-duplicated vertex, to its last non-duplicated vertex. Previously we failed to check if the last index was a duplicate, which caused rendering errors as seen [here](https://github.com/tangrams/tangram/issues/457).
Also previously, our check for duplicates in the beginning of the line was to simply remove it and create a new array to iterate through. This PR avoids creating this extra memory. And it handles multiple duplicate vertices in the beginning and end of lines gracefully.
> Avoid duplicate vertices in lines. Fix 457

- src/styles/text/canvas_text.js
- src/styles/text/text.js
- src/styles/text/text_settings.js
This is a follow-up to #458. The pixel-snapping technique used there can only be applied to fully upright labels, such as for POIs. A different technique can be used to improve the clarity of angled labels, such as for roads:
By rendering the underlying label texture at a larger initial size, we can get better results when it is sampled during rotation. @meetar and I tried a few values and found that rendering at 150% of display size seems to give the best results (200% introduces new aliasing / over-sharpness by actually providing too many pixels to sample from).  
This significantly improves clarity for non-Latin scripts and small font sizes (though helps for all diagonal labels in any script).
Animated before-and-after:
Side by side diff:
@dmvaldman this may require careful merging …
> Improve text clarity for angled labels by supersampling text rendering

- demos/scene.yaml
- src/styles/layer.js
- src/styles/style.js
- src/styles/style_manager.js
Allows a rendering style to include defaults for `draw` parameters (that can then be overridden or supplemented as normal when the style is used in a draw group under `layers`).  See #489 for background.
Example, setting a default `size` for icons:
```
styles:
icons:
base: points
texture: icons
draw:
size: 16px # default size
layers:
...
draw:
icons:
sprite: coffee
```
This new capability does raise an unusual syntax issue though, which is that in some cases, the style definition may now include *all* the required draw parameters, but a draw group referencing that style must still be added in `layers` to invoke the actual draw operation.
With current Tangram JS behavior (unsure about ES), a `null` draw group will fail validation, and nothing will be drawn. Therefore, adding an all-default …
> Styles can specify default `draw` parameters

- src/styles/filter.js
As I'm playing around with the (super easy-to-use! really wonderful) tangram library, in the context of playing around with the new Walkabout mapping layer, I'm consistently seeing this error message and my eyes can't help but fixate on the typo. I realize this is not the most helpful kind of PR to receive, but I figured I'd post it anyways!
> Correcting error typo in filter.js

- src/styles/text/canvas_text.js
Found a BIDI bug. Previously we were allowing bidirectional text to curve. Now only strongly directional text can curve.
> Fix to prevent BIDI-text from curving

- demos/main.js
- demos/scene.yaml
- src/styles/layer.js
As discussed in https://github.com/tangrams/tangram-docs/issues/198:
- Renames the layer-level `visible` property to `enabled`, to prevent confusion with the *`draw` group-level `visible` property*, which continues to exist as-is.
- Provides backwards compatibility for the previous `visible` property name: if the `enabled` parameter is undefined for a given layer, any value for `visible` will be used instead.
- Changes the Tangram JS treatment of the layer `enabled` (nee `visible`) parameter to match that of Tangram ES: once set by a layer, the parameter *cannot* be overridden by any descendant layers.
- This provides a mechanism to cull large portions of the layer tree, with the guarantee that they will stay hidden. This is especially useful as more optional overlay-style layers are …
> Rename layer `visible` -> `enabled` & don't allow descendant layers to override

- demos/scene.yaml
- src/labels/label_line.js
- src/styles/points/points.js
- src/styles/points/points_vertex.glsl
- src/styles/text/canvas_text.js
- src/styles/text/text.js
- src/styles/text/text_labels.js
(cleaned up and rebased version of previous PR https://github.com/tangrams/tangram/pull/506)
This PR addresses #471 where we were not previously using the orientation of a line to modify an offset of a label. This allows a line label to remain on a specific side (inside or outside) of a polygon as it is placed around the polygon's boundary.
The offset will follow the geometry orientation if both an offset is specified and the text_source is given as an object with a `left`, and/or `right` key. For example
```
draw:
text:
text_source:
left: 'name:left'
right: ‘name:right'
offset : [0, 10px]
```
> Oriented offsets for boundary lines

- .gitignore
- build/quine.js
- package.json
- src/scene.js
This makes the source map filename used for workers a parameter passed to the `quine.js` plugin. This addresses two issues:
- Fixes an issue where the source maps would not be correct for worker threads if the Tangram bundle was renamed to a different filename, since it was relying on the origin (via `document.currentScript`) to construct the source map URL for workers.
- Allows the `budo` live-reload process to write to a temp source map name (which is in `.gitignore`), preventing it from conflicting with the official build filenames in `dist/`.
The downside is that the source map name has to be explicitly passed in to the plugin, but this was already true for the call to `mapstraction`.
> Make source map filename configurable

- src/labels/label_line.js
Makes all vertical labels point up, instead of be a mix of up and down. Fix for https://github.com/tangrams/tangram/issues/517
> Uniform vertical labels

- src/styles/text/canvas_text.js
We detect if a broken up text segment ends on a neutral character. In this case we draw the characters individually (as separate glyphs) instead of clustering them. This should resolve the issue with curved labels for RTL text, but not for multi-line labels, which will require a different approach. This fixes part of the issue in #541.
Spaces:
Punctuation:
> Fix #541 RTL curved labels when segments end on neutral character

- demos/main.js
- src/builders/points.js
- src/builders/polygons.js
- src/builders/polylines.js
- src/leaflet_layer.js
- src/scene.js
- src/scene_worker.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons.js
- src/styles/style.js
- src/tile.js
- src/utils/debug_settings.js
Adds a `layer_stats` debug option, which will enable collection of feature and geometry stats per layer:
- Number of features that were built for each layer
- Number of GL geometries (triangles) that were built for each layer
- GL geometry counts are further collected by rendering `style`, and grouped by style `base` (e.g. `polygons`, `lines` etc.)
These stats are collected in two formats:
- A flattened **list** that displays all of fully qualified layer names, e.g. `roads:path:bridge`
- A **tree** that aggregates counts at each level of the layer tree, with the ability to drill down into descendant levels
Counts for the tiles in the **current view** can be retrieved through `scene.debug.layerStats()` (a warning is logged if the `layer_stats` debug option is not enabled). This method …
> Adds debug option to collect per-layer stats

- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/points/points_fragment.glsl
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons.js
- src/styles/style_manager.js
- src/styles/text/text.js
- src/styles/text/text_fragment.glsl
In `points`-based styles, Tangram JS has been applying any shader blocks to any `text` attachments for that style, e.g.:
```
styles:
tinted:
base: points
shaders:
blocks:
filter: color.r += 0.5;
layers:
...
draw:
tinted:
... # shader blocks applied to these points
text:
... # shader blocks ALSO applied to this text
```
This branch changes that behavior so that these shader blocks **will not** be applied to the attached `text`. This is for two reasons:
- While it can be useful to apply shader blocks to text for some effects (which is still possible with the standalone `text` style), it can be problematic to require the *same* blocks apply to both the point and text portions; this recently arose when working on adding tinted icons to Refill.
- Tangram ES already does *not* apply these …
> Do not apply shader blocks on `points`-based styles to attached `text`

- src/styles/text/canvas_text.js
I saw Mapzen's [blog post](https://mapzen.com/blog/curved-labels) about curved labels awhile ago and was interested in how I could expand it to more languages
Burmese (pictured above) has some text-shaping - for example the word "ဟို" is three chars long. But it's similar to how "ý" can be two chars. Burmese doesn't connect all letters like Arabic or Devanagari. By counting grapheme clusters instead of chars, we can prevent both writing systems from being split up irregularly. That's what this pull request fixes.
The RegEx is long because it includes other writing systems (at least Latin alphabet, Devanagari and Tamil), but I have not enabled or tested them in curved labels yet.
In the future it would be possible to use [Intl.Segmenter or a …
> Make curved labels in more languages

- src/leaflet_layer.js
- src/scene.js
- src/scene_bundle.js
- src/scene_loader.js
This adds an optional `file_type` for the `scene.load()` method (and `sceneFileType` for the Tangram Leaflet layer constructor). This allows for zip files to be loaded without .zip extension (previously, the filename had to end in '.zip' to trigger zip-loading).
This is useful for cases like loading a blob URL that contains a zipped scene file (see #565). For example:
`scene.load(zip_blob_url, { file_type: 'zip' });`
or 
```
layer = Tangram.leafletLayer({
scene: zip_blob_url,
sceneFileType: 'zip',
...
});
```
This also updates internal naming of `scene.config_path` to more intuitive `scene.base_path`. The existing `scene.config_path` accessor will be maintained for now, but eventually deprecated. Options to `scene.load()` should also be passed as an object, e.g.:
`scene.load(scene_url, { …
> Add optional `file_type` for scene.load()

- src/sources/data_source.js
- src/tile.js
- src/tile_manager.js
- src/tile_pyramid.js
- src/view.js
- test/tile_pyramid.js
See https://github.com/tangrams/tangram-es/issues/1435 for details
Data sources can enable larger tile sizes:
```
sources:
mapzen:
type: ...
url: ...
tile_size: 512px
```
`tile_size` must be a power of 2 greater than or equal to 256, and can optionally include `px` units.
> Add support for 512px (and beyond) tile sizes

- src/scene.js
- src/utils/media_capture.js
Adds an optional background color that will be blended with any translucent pixels in the scene when capturing a screenshot. In normal browser presentation, these pixels are blended with whatever HTML content is behind them. With this optional parameter, users have more control to achieve similar when capturing a screenshot.
The existing `scene.screenshot()` method signature is expanded to support a `background` parameter:
`scene.screenshot ({ background = 'white' }`
The `background` parameter defaults to `white`. This is because while the Tangram scene's default background is `transparent`, it is always viewed against an opaque browser background (which itself defaults to white, absent any user styling). As such, a default screenshot background color of white is most likely to match the …
> Add background color parameter for screenshots

- src/leaflet_layer.js
- src/scene.js
- src/selection.js
This PR adds an optional pixel radius when requesting features at/near a pixel location. Previously, feature selection only returned a feature at the *exact* pixel location provided, but there are common use cases where a larger radius is useful, such as:
- Mobile devices where input is not always so precise
- Features such as thin lines may be difficult to select
The following methods are affected:
- Direct scene interface:
- `scene.getFeatureAt(pixel, { radius })`
- Leaflet layer interface for setting selection handlers
-  `layer.setSelectionEvents (events, { radius })`
- Leaflet layer instantiation: 
```
layer = Tangram.leafletLayer({
scene: 'path/to/scene.yaml',
events: {
click: clickHandler,
},
selectionRadius: 10
};
```
In all cases, `radius` or `selectionRadius` is an optional …
> Add optional pixel radius for feature selection

- src/geo.js
- src/scene.js
- src/scene_worker.js
- src/styles/layer.js
- src/styles/points/points.js
- src/styles/style.js
- src/styles/style_parser.js
- src/styles/text/text.js
- src/utils/slice.js
- src/utils/utils.js
- src/utils/worker_broker.js
This PR adds a `Scene.queryFeatures()` method for directly querying tile data (separate from the existing [`Scene.getFeatureAt()`](https://mapzen.com/documentation/tangram/Javascript-API/#getfeatureatpixel) method, which returns a single feature at a given pixel location).
The query method has the following signature and default parameters:
`queryFeatures({ filter = null, visible = null, unique = true, group_by = null, geometry = false })`
- `queryFeatures()` will query the features from tiles that **currently intersect the map viewport**.
- The method returns a promise with an array of matching features, e.g. `queryFeatures().then(features => console.log(features));` will print the matching features to the console. (An array is the default return type, see `group_by` below for an …
> Adds the ability to query features from tile data

- demos/scene.yaml
- src/scene.js
- src/styles/style.js
This is the JS equivalent of https://github.com/tangrams/tangram-es/pull/1615.
Adds a `blend: translucent` mode, that provides alpha blending for front-facing polygons (still culls back-faces). 
This branch adds a stencil buffer to our GL context, which is used to prevent repeated/overlapping polygons (e.g. buildings that may be repeated across tiles, or features rendered in proxy tiles) from drawing multiple times and causing undesirable compounding of the alpha channel.
> Add translucent blend mode

- src/gl/texture.js
- src/styles/style.js
When one or more of a style's attached raster texture fail to load (404 or other error), throw out the style for that tile. This fixes the issue in #598, where unavailable raster tiles would cover up areas of the map underneath.
> Skip style when raster textures fail to load

- demos/scene.yaml
- src/scene.js
- src/scene_loader.js
- src/styles/layer.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons.js
- src/styles/polygons/polygons_fragment.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style.js
- src/tile.js
This PR relaxes the requirement that the `dash` pattern for `lines` styles be bound to a single pattern defined at the `styles` level.
With this change, a scene author can freely re-assign (or un-assign) the dash pattern that the style is bound to, within a `draw` group, using the `dash` parameter.
For example:
```
layers:
roads:
data: ...
draw:
lines: # by default, draw roads with NO dash pattern
width: 5px
color: white
...
paths:
filter: { kind: path }
draw:
lines:
dash: [2, 1] # draw paths with a dash pattern
...
ferries:
filter: { kind: ferry }
draw:
lines:
dash: [1, 3, 1] # draw ferries with a different dash pattern
...
```
This change is fully backwards compatible with existing `styles`: if a style has set a `dash` pattern set, this simply becomes the default value, but that value …
> Dynamic line dash patterns

- package.json
- src/sources/mvt.js
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
> Use @mapbox/vector-tile

- package.json
#606 set an implicit NPM version requirement, this makes it explicit.
I'm not sure if NPM 1.x will error with this or not, but it at least sets the acceptable version range.
> Set the minimum NPM version

- package.json
Tangram has not been buildable on Windows, mostly do to some small syntax issues (see #569).
This PR makes a couple adjustments that improves the experience. The following flows have been tested on Windows 10:
- Live reload (`npm start`) on PowerShell (in Windows and bash modes), Bash for Windows, and Git Bash.
- Full package build (`npm run build`) on PowerShell (bash mode only, relies on unix pipes/commands), Bash for Windows, and Git Bash.
> Improve the Windows dev/build experience

- build/quine.js
in some cases document.currentScript can be null, on that case the
condition resolves to true and fails to get the src attribute from null
ending with an exception.
this change checks that currentScript is truthy (not null nor undefined)
in the condition
closes #625
> currentScript should be truthy, not !== undefined

- src/sources/data_source.js
- src/sources/geojson.js
- src/sources/topojson.js
To enable support for formats that may contain geographic data, but not be formatted in the commonly supported formats (GeoJSON, MVT, etc.), this PR adds a data source `preprocess` option. This parameter can define a JS function to mutate the **raw** network response fetched by a data source, before it is processed further. This is similar to the existing `transform` function, with the difference that `transform` is called *after* initial response parsing (e.g. decoding TopoJSON and MVT to GeoJSON-style data).
The `preprocess` function should return data in the format expected by the data source type, e.g. if `type: GeoJSON`, then `preprocess` should return a GeoJSON object.
For example, given a Who's On First CSV export (which contains geographic data in the form of census interior …
> Support CSV and other formats with data source `preprocess` option

- src/gl/texture.js
- src/styles/points/points.js
- src/styles/style_parser.js
Currently, `points` styles which do not have sprites defined can only specify `size` in fixed values of `px`. Additionally, setting a `density` in the texture definition has no effect.
This PR will allow points styles to use percentages (`size: 50%`) and ratios (`size: [16px, auto]` or `size: [50%, auto]`), and will use `density` in css_size calculations.
Fixes #638, fixes #642, and fixes #644.
> apply %s, ratios, and density to textures in points

- src/builders/polygons.js
- src/styles/style.js
**Steps to reproduce the bug:**
Open the [Tangram Play](https://tangram.city/play/?#2/0/0)
and set this YAML definition:
```
sources:
geojson:
type: GeoJSON
url: https://gist.githubusercontent.com/germanz/e0fc172fa458bd50c17bbac9b24e17e0/raw/a1f9bb86265c0ae1c72fc37b99b2967fb302faaa/polygon_with_hole
scene:
background:
color: black
layers:
layer:
data: {source: geojson}
draw:
polygons:
color: red
order: 1
```
A red rectangle with a rectangular hole is rendered as expected.
Zoom in until you see render artefacts like this:
> Quick fix for Polygons with interior (holes)

- src/styles/points/points.js
@burritojustice noticed that the return value for a JS function on a `points` style `angle` property is treated as radians, instead of degrees, e.g.:
- static values like `angle: 90` are treated as degrees (correct!)
- function values like `angle: function() { return 90 }` are treated as **radians** (wrong!)
This PR corrects behavior to expect a return value in degrees, and converts it to radians.
Also see https://github.com/tangrams/tangram-docs/issues/250.
> `angle` JS functions should treat return value as degrees

- index.html
- src/leaflet_layer.js
- src/scene.js
- src/scene_worker.js
- src/styles/lines/lines.js
- src/styles/polygons/polygons.js
- src/styles/style.js
A few optimizations to improve performance for feature selection:
- Skip feature selection rendering entirely when there are no `interactive` features currently rendered in the scene (either because the style doesn't specify any, or just if they are not in the current visible tile set).
- Lazily instantiate feature selection resources the first time a selection render pass is needed. Specifically, this avoids allocating a GL framebuffer until it's needed, which is a significant savings / delay in memory usage.
- Also clear these resources when a new scene is loaded (new scene may not have any interactive features).
- Using the "mesh variants" capability developed for line offsets (which allows for doing multiple draw calls per style, with different vertex layout and/or uniform values), …
> Feature selection optimizations

- src/sources/geojson.js
- src/sources/mvt.js
- src/sources/topojson.js
This makes per-tile data transformations possible, including debugging data. For example, this creates a polygon at the tile boundaries, named for its source tile:
```javascript
transform: |
function(data) {
t = this.tile;
c = Tangram.debug.Geo.metersToLatLng;
min = c([t.min.x, t.min.y]);
max = c([t.max.x, t.max.y]);
return {
type: 'FeatureCollection',
features: [{
type: 'Feature',
geometry: {
type: 'Polygon',
coordinates: [[
[min[0], min[1]], [max[0], min[1]],
[max[0], max[1]], [min[0], max[1]],
[min[0], min[1]]
]]
},
properties: {
name: this.tile.coords.key
}
}]
};
}
```
Addresses https://github.com/tangrams/tangram/issues/354.
> make tile available in source transform function

- src/scene_worker.js
See #671 for background. This branch takes a different approach to enable the same support (and more!) for `queryFeatures()`, but with a smaller code change footprint and API change.
It adds properties for `$source`, `$layer`, and `$geometry` to the features returned by `queryFeatures()`. You could already `filter` these in `queryFeatures()` calls (using the same filter syntax we use in the scene file), but this allows you to also use the `group_by` feature with them. In addition, a `$visible` property was added. While this property (by definition!) doesn't exist for a scene file `filter`, it's a logical extension here.
You can do some neat things with these options, such as:
Features grouped by layer (with feature count for each):
`scene.queryFeatures({ group_by: '$layer' })`
Features …
> Add $source, $layer, $geometry, and $visible properties for queryFeatures()

- demos/scene.yaml
- src/sources/data_source.js
- src/utils/utils.js
Following up on #668: to enable cases where a client would like to send additional, custom HTTP headers with each tile request.
A data source can specify key/value pairs for header names/values, with the `request_headers` parameter. For example, if the tile backend is authorized with and OAuth token:
```
sources:
tiles:
type: TopoJSON
url: ...
request_headers:
Authorization: Bearer XXXXXX
```
While `request_headers` *can* be specified statically in the scene file, it's more likely they would be added programmatically at run-time (they could either be added after a scene `load` event, or by directly modifying `scene.config` and calling `scene.updateConfig()`). They would also generally be expected to be used with custom tile sources.
CORS
------
If the tile source is being made via CORS …
> Data sources can specify optional request headers

- src/scene.js
- src/scene_loader.js
Changes how `global` property substitution is applied, to fix an edge case where globals were too "sticky": once a property had a global value substituted, it could never be "un-linked" from that global, even if directly modified in the `scene.config` object.
Example, for a global:
```
global:
color: red
```
Referenced in a draw block:
```
layer:
draw:
color: global.color
```
When the scene is loaded, the `global.color` value will be applied, and the draw `color` will be `red`.
If the value is then modified in JS:
```
scene.config.layers.layer.draw.color = 'blue'; // set to an explicit, non-global value
scene.updateConfig();
```
The original global linkage would "stick", and the final `color` would still be `red` (instead of the new `blue` value)! This is a rare but frustrating issue, …
> Use getters/setters to fix "sticky" global property edge case

- src/index.js
- src/scene.js
- src/scene_worker.js
- src/styles/layer.js
- src/styles/style_parser.js
- src/utils/functions.js
- src/utils/utils.js
This caches user-defined JS functions for the scene (e.g. for filters, colors, etc.) by their unique source code. This can lead to substantial decrease in the number of functions that have to be compiled when using globals. On Mapzen/Nextzen styles, the reduction is anywhere from 40% (on Bubble Wrap) to almost 300% (on Walkabout). Additionally, the cache is cleared when a new scene is loaded, so these functions can be freed.
> Cache user-defined JS functions

- src/labels/collision.js
- src/labels/label.js
- src/labels/label_line.js
- src/labels/label_point.js
- src/labels/main_pass.js
- src/styles/points/points.js
This fixes repeat behavior across tiles for labels that don't have regular collision applied (e.g. `collide: false`). These labels had repeat culling applied *within* the tile, during the initial tile build on the worker thread, but did not have an additional repeat culling pass applied later on the main thread, to catch repeats from nearby tiles (labels with `collide: true` *did* already have this additional check; `collide: false` labels skip part of the collision pipeline for speed, and were inadvertently missing this piece).
This is solved with an additional flag that tracks whether the label is less than its repeat distance away from the tile edge. If so, it may need to be culled with labels from nearby tiles; if not, it's far enough away to not be affected by them.
Here's an example …
> Fix repeat culling on main thread for non-collision labels

- src/gl/vao.js
- src/gl/vbo_mesh.js
- src/gl/vertex_layout.js
- src/styles/polygons/polygons_vertex.glsl
Several features make use of static GL vertex attributes, e.g. set with `vertexAttrib4fv()` etc. methods, unlike dynamic per-vertex "array" attributes set with `enableVertexAttribArray()` and `vertexAttribPointer()` methods).
These fixed vertex attribute calls were being made along with the rest of the Vertex Array Object initialization. However, it turns out that this state is NOT part of the VAO state. From the [OpenGL VAO docs](https://www.khronos.org/opengl/wiki/Vertex_Specification#Non-array_attribute_values):
> A vertex shader can read an attribute that is not currently enabled (via glEnableVertexAttribArray). 
The value that it gets is defined by special context state, which is *not* part of the VAO.
This discrepancy likely hasn't been frequently observed because we have only used …
> Ensure static GL attributes are enabled outside VAOs

- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons_vertex.glsl
@hanbyul-here found that one of @patriciogonzalezvivo's old maps -- https://github.com/tangrams/WeatherOverTime -- was not working anymore due to a shader compilation error showing conflicting `#define PI` definitions.
It turns out a `#define PI` was added to Tangram's `points` vertex shader back when curved label support was added: https://github.com/tangrams/tangram/pull/484/files#diff-5c9ade004b24e8b556a6b8b8e9d3096fR24
To avoid these conflicts, we should namespace built-in shader defines with `TANGRAM_`. Most already do this, but this PR catches two that didn't.
> Namespace built-in shader defines

- src/gl/vertex_layout.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons.js
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style.js
- src/styles/text/text.js
Improve GPU memory usage for `polygons` and `lines` styles with some vertex attribute VBO re-arrangement.
- For `polygons`:
- Features that aren't extruded don't need per-vertex surface normals, because they're always flat and facing up. We can make the `a_normal` attribute have a static value of `[0, 0, 1]` in these cases. Extruded features like buildings keep the full per-vertex `a_normal` in the VBO.
- For `lines`:
- This one is a bit trickier. Both the z position of the feature (e.g. the `z` parameter in a `draw` block, which moves the entire line up and down in space) and line `offset` are optional. 
- While the `a_offset` attribute (different from the line's `a_extrude`, which diverges from the line normal at caps and joins) was already an optional attribute with a static value of …
> Optimize attribute packing to lower GPU memory usage

- src/styles/points/points.js
- src/styles/text/text_labels.js
This fixes an issue with label repeat group logic. The intended behavior is for labels to apply repeat rules **within their unique scene layer group**. For example, labels for a major and minor road with the same name *will* be allowed to repeat near each other. This was intended to catch uncommon but still existent cases where labels of different feature classes are desirable to show.
However, now that the bug is fixed, I notice that there are some suboptimal cases in Mapzen styles where extra labels are being shown nearby to each other and a bit crowded -- often 2 but sometimes even 3 -- because they are different road types, including ramps, etc. See the extra Market St and Park Row labels below:
This can be addressed in the style by putting all of the road labels into one …
> Fix label default repeat groups

- src/gl/texture.js
- src/scene/scene.js
- src/styles/lines/lines.js
- src/styles/style.js
- src/styles/style_manager.js
- src/styles/text/text_labels.js
- src/tile/tile_manager.js
- src/utils/worker_broker.js
Fix memory leak when `scene.updateConfig()` is called, due to dangling style references in `WorkerBroker` (outdated style worker broker targets were not removed when new styles were built).
See discussion in https://github.com/tangrams/tangram/issues/696. Thanks to @rihteri!
> Fix `scene.updateConfig()` memory leak

- src/sources/data_source.js
- src/sources/raster.js
This adds support for `@2x`-style tile filenames, often used for high-density raster tiles. For this implementation I opted to follow the same, simple logic as Leaflet, which is:
A `{r}` URL template substitution option, which adds the string `@2x` for any device with a device pixel ratio > 1.
CartoDB basemap example:
```
sources:
raster:
type: Raster
url: https://a.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png
```
- On a device with device pixel ratio <= 1: `https://a.basemaps.cartocdn.com/light_nolabels/14/4823/6163.png`
- On a device with device pixel ratio is > 1: `https://a.basemaps.cartocdn.com/light_nolabels/14/4823/6163@2x.png`
Note, while this syntax is traditionally used with raster tiles, this implementation also applies to vector tiles (which could conceivably be …
> Add URL template support for @2x tiles

- src/styles/raster/raster_globals.glsl
In doing some raster tests, @meetar found that the built-in `sampleRasterAtPixel()` raster shader method was not working properly when using mixed tile sizes, for example a 256px vector tile source with an attached 512px raster tile source. While the default / more common `sampleRaster()` method (used in the default raster style implementation) was working properly in this scenario, the explicit pixel look-ups were scrambled, with incorrect UV offsets. An example of the correct vs. actual results:
Digging in, it looks like the `sampleRasterAtPixel()` method was incorrectly applying a call to `adjustRasterUV()`, which is used to correctly offset tile UVs from smaller (e.g. 256px) tiles inside of a larger (e.g. 512px) raster tile texture. This adjustment is used in `currentRasterUV()`, …
> Fix raster sampling at explicit pixel locations with mixed vector/raster tile sizes

- src/sources/data_source.js
Some tile sources, such as Microsoft's aerial imagery and HERE's XYZ vector API, use the quadkey URL scheme (as an alternative to the x/y/z URL pattern), as described here: https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system
This PR adds support for this alternative, through the `{q}` URL token. For example, here is a mix of Microsoft aerial imagery, with Nextzen place labels atop:
```
sources:
msft:
type: Raster
url: https://ecn.t3.tiles.virtualearth.net/tiles/a{q}.jpeg?g=587
nextzen:
type: MVT
url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.mvt
tile_size: 512
max_zoom: 16
layers:
msft:
data: { source: msft }
draw:
raster:
order: 0
places:
data: { source: nextzen }
draw:
text:
font:
family: Helvetica
size: 12px
fill: white
```
Data sources are now …
> Quadkey support for tile URL templates

- src/scene/scene.js
- src/styles/points/points.js
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style.js
- src/tile/tile.js
This PR eliminates a long-standing, nasty artifact that occurs with features rendered with non-`opaque` blend modes when zooming -- as one or more levels of proxy tiles are rendered on top of each other (and/or with the new tile that is loading to replace them), the compounding alpha causes a flickering effect.
This PR avoids these artifacts using the stencil buffer: proxy tiles are drawn from front to back, with the stencil buffer adjusted for each level (e.g. zoom ancestor or descendant level) such that proxies will only draw pixels not previously covered by a previous level. Note, it's important that pixels from proxies are allowed to overwrite other pixels from the *same* proxy level, for overlapping geometries to render properly; we just want to mask out pixels from other, previously …
> Mask non-`opaque` proxy tiles with stencil buffer

- src/scene/scene.js
- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons.js
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style.js
- src/styles/style_manager.js
- src/styles/text/text.js
- src/tile/tile.js
- src/tile/tile_manager.js
For styles drawn with non-`opaque` blend modes, the `blend_order` is used to determine the rendering order, and thus which features are drawn on top of each other where there are overlaps. 
Because it has only been possible to set `blend_order` at the `style` level, a common pattern has developed where several very similar / template rendering styles are created, to achieve different visual layering:
```
polygons-overlay-low:
base: polygons
blend: overlay
blend_order: 1
polygons-overlay-mid:
base: polygons
blend: overlay
blend_order: 3
polygons-overlay-high:
base: polygons
blend: overlay
blend_order: 5
```
This is inefficient and unwieldy -- and inflexible, especially when mixing data on top of basemaps (which end up having to predefine certain fixed `blend_order` "slots" for use by data …
> Enable setting of `blend_order` at the `draw` level

- demos/scene.yaml
- src/index.js
- src/sources/data_source.js
- src/sources/geojson.js
- src/sources/raster.js
- src/tile/tile_id.js
- src/tile/tile_pyramid.js
- test/tile_pyramid.js
- test/tile_spec.js
Currently, tiled data sources request data at every map zoom level. There are some parameters that affect the mapping between the "view" zoom and the "tile" zoom (`tile_size`, `zoom_offset`), but these still trigger a new load at each zoom level.
There are some cases where it may be unnecessary or undesirable to load new tile data this frequently. This PR extends the syntax for data sources, with a new `zooms` parameter that can specify a list of zoom levels at which new data should be loaded.
For example, to only load new tile data at every other zoom level:
```
sources:
tilezen:
type: MVT
url: ...
zooms: [0, 2, 4, 6, 8, 10, 12, 14, 16] # only load tiles every 2 zooms
```
Or, an application with two logical levels -- such as a zoomed out and zoomed in view -- could define these …
> Data sources can define specific zoom levels at which tiles are loaded

- src/styles/layer.js
- test/layer_spec.js
This PR introduces two new keywords -- `priority` and `exclusive` -- for scene `layers`, to enable greater control over feature filter matching and styling composition.
**Background**
Tangram layer matching has always been inclusive, meaning a feature can match multiple layers (at multiple levels of the layer style tree), which are then merged to determine the final rendering parameters. Composing complex sub-layer trees can be used to capture both feature and zoom-dependent styling along orthogonal dimensions, for example varying road line widths and colors by separate criteria.
However, two in many ways simpler behaviors have *not* been easily expressed with the current layer syntax:
- The priority with which layers are matched has always been implicit. While layer depth takes priority …
> More layer matching control with `priority` and `exclusive`

- src/labels/main_pass.js
- src/styles/points/points.js
- src/styles/points/points_vertex.glsl
- src/tile/tile_manager.js
Improvements to label behavior on zoom out:
- Run collision more frequently (don't block on user input).
- Allow proxy labels to keep displaying, but only if they were previously visible (e.g. collision can remove visible proxy labels, but not add new ones that weren't already visible).
- Clamp curved label zoom interpolation factor (so curved labels don't go wild when zoomed beyond 1x up/down).
- Don't fade proxied labels out when zoomed beyond 1x (was only there to hide unsatisfactory proxy collision behavior addressed by above changes).
> Label zoom out improvements

- src/sources/mvt.js
- src/styles/filter.js
- src/styles/layer.js
Sometimes source data includes properties with a richer object format than just strings or numbers -- e.g. arrays, nested objects, etc. The MVT spec [doesn't prescribe explicit behavior](https://docs.mapbox.com/vector-tiles/specification/#how-to-encode-attributes-that-arent-strings-or-numbers) for these cases, but notes that common tools such as [Tippecanoe](https://github.com/mapbox/tippecanoe) and Mapnik will encode these properties as stringified JSON.
This requires client-side support for parsing these fields. This PR adds support for this on MVT data sources through a new `parse_json` property:
- If `parse_json` is `true`, then *each* property will be checked to see if it "looks like" stringified JSON (defined as a string with first character being `{` or `[`); if so, it is parsed as …
> Add support to parse some or all MVT feature properties as JSON

- src/labels/collision.js
- src/labels/collision_grid.js
- src/labels/main_pass.js
Previously, the collision system has been brute force for all labels (points and text labels with collision enabled) in the current set of visible tiles. As labels are placed, every new label candidate is tested against every previously placed label.
This brute force approach has been fine (and often faster than adding indexing schemes which bring their own overhead) with typical / small sets of labels, e.g. ~1000. As label density grows, it get quadratically slower, and with large (e.g. 100,000 points) sets it is essentially unusable (multi-second collision passes). These cases have not arisen in typical Tangram basemap scenes, but easily can with dataviz (in many cases you have collision *off* for these large sets anyway... but you still want a practical way to turn them on for some use …
> Add a collision grid for better performance of high density point/label scenes

- src/scene/scene_loader.js
This PR attempts to ease another common pain point with blend modes, as a follow-up to enabling `blend_order` to be set at the `draw` level in #703. 
In this case, the goal is to make it easier to use the different `blend` modes without having to write boilerplate styles. However, this PR takes a different approach than was used for `blend_order`. For each combination of `blend` mode (`opaque`, `overlay`, etc.) and style `base` (`polygons`, `lines`, etc.), a style is automatically created at scene load-time with the naming scheme `blend_base`, e.g. `translucent_polygons`, `overlay_lines`, etc. Each of these is a minimal style definition, such as (if expressed in YAML):
```
translucent_polygons:
base: polygons
blend: translucent
```
In effect the PR expands the set of built-in styles by …
> Automatically add default blend/base style pairs

- src/scene/scene.js
- src/scene/scene_worker.js
- src/sources/geojson.js
- src/sources/mvt.js
- src/styles/style_parser.js
All data formats supported by Tangram have a `feature.id` property (at the top `feature` level, outside `feature.properties`; some data sets may separately include an id or similar property within `feature.properties`), but we haven't had full support for it. This PR fixes that:
- Ensures `feature.id` persists wherever features are internally copied/synthesized/etc. internally
- Provides access to `feature.id` in user-authored JS scene functions with a new `$id` variable
- Includes `feature.id` in feature object results returned from `scene.queryFeatures()`
- Includes `feature.id` in the default uniqueness check for `scene.queryFeatures()`, with `$id` syntax used if specifying a list of properties to uniqueify on, e.g.:
- For default `scene.queryFeatures({ unique: true })`, `feature.id` …
> More robust support for `feature.id`

- src/gl/context.js
- src/scene/scene.js
Defaults to using `high-performance` for WebGL's `powerPreference` setting. This will ask for use of the discrete GPU where possible. The user can override as with other GL context options:
```
const layer = Tangram.leafletLayer({ scene, { webGLContextOptions: { powerPreference: 'low-power' } } });
```
> Default to WebGL "high performance" mode

- src/scene/scene_bundle.js
- src/sources/data_source.js
- src/styles/text/font_manager.js
- src/utils/utils.js
- test/data_source_spec.js
Fixes #729.
Adds support for HTTP 204 (No Content) responses in tile requests. Any tiles returning a 204 will be considered to have loaded successfully, but will simply be empty. Previously these requests would cause warnings as a non-200 response.
> Support HTTP 204 response

- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/polygons/polygons.js
- src/styles/text/text_labels.js
- src/styles/text/text_settings.js
This PR adds a new `alpha` parameter inside several `draw` group contexts. It allows the scene author to set *only* the alpha channel of a color, independently of the RGB channels.
Use cases where this is helpful include:
- Modifying the alpha for named CSS colors
- Modifying the alpha channel in a sub-layer, which can simplify complex layer trees or help with cases where you may be importing/overriding another style, or applying "themes" that change the underlying base colors
- Using a feature property to set the color, but then modifying only the alpha (note, this was not easily achievable before in cases where a feature property might contain a hex or CSS named color), e.g. use transit line colors encoded in tiles, but draw lines at 75% opacity
- Applies to the following styles in …
> Optional `alpha` parameter for `draw` groups

- src/styles/lines/lines.js
- src/styles/points/points.js
- src/styles/points/points_fragment.glsl
- src/styles/points/points_vertex.glsl
- src/styles/polygons/polygons.js
- src/styles/polygons/polygons_fragment.glsl
- src/styles/polygons/polygons_vertex.glsl
- src/styles/style.js
- src/styles/style_manager.js
- src/styles/text/text.js
This PR adds support for custom vertex attributes/varyings in user-defined styles. This simplifies existing uses of per-feature property data in shaders, which are usually "smuggled" into the shader by encoding non-color values in the `color` parameter, by moving these values to more semantic-appropriated attributes names/formats, and also preserving the `color` attribute for its intended use. It also enables more advanced forms of custom shader visualizations, by allowing for multiple attributes to be defined, and with the potential for more datatypes (only `float` is covered in the initial PR).
- A new `attributes` object is available under a style's `shaders` block.
- Each key under `attributes` specifies an attribute name, and the value specifies the attribute type and other options. …
> Styles can define custom vertex attributes

- src/styles/lines/lines.js
- src/styles/polygons/polygons_fragment.glsl
This PR revamps the logic for applying line dash patterns and textures. The prior logic had some holes and inconsistencies, including #741. It implements the following logic in the fragment shader for lines (and also replaces some conditional `if/else` shader branching with nested `mix` functions):
- A line can have an active texture sampler in two cases:
- Implicitly, through a `dash` pattern (the texture is automatically generated from the dash pattern).
- The dash pattern defines a foreground color (via the regular `color` parameter, available in the shader as the vertex `color`) and background color (via the `dash_background_color` parameter, available in the fragment shader as `u_dash_background_color`).
- The dash texture is a monochrome representation of the pattern, with opaque …
> Fix line dash color handling

- package-lock.json
- package.json
I was seeing some sliver polygons being created - was resolved by bumping `earcut` to the latest. also regenerated the package-lock.json
> bump earcut version

- src/styles/text/font_manager.js
- src/styles/text/text_labels.js
- src/styles/text/text_settings.js
[Variable fonts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide) allow multiple variants of a font to be stored in a single file. 
Supporting these has several benefits:
- Streamlines the Tangram font definition, e.g. for example instead of 
```
Open Sans:
- weight: 200
url: fonts/Open Sans.woff2
- weight: 400
url: fonts/Open Sans.woff2
- weight: 600
url: fonts/Open Sans.woff2
- weight: 800
url: fonts/Open Sans.woff2
```
we can do
```
Open Sans:
url: fonts/Open Sans.woff2
weight: 200 800
```
- Reduces network requests, requesting one file instead of many.
- Introducing new cartographic flexibility, as some variable fonts can render at intermediate weights along the spectrum, not just at predefined weights.
In CSS, the syntax for variable font weight looks …
> Support variable font weight ranges + JS function weights

- src/styles/style_parser.js
- src/styles/text/text_canvas.js
- src/styles/text/text_labels.js
- src/styles/text/text_settings.js
- src/utils/utils.js
See #724. Adds support for an optional box behind text labels, which adds the following parameters, in a new `font.background` block:
- Text box **fill color**
- `font.background.color`
- Optionally vary alpha independently: `font.background.alpha`
- Text box **stroke color**
- `font.background.stroke.color`
- Optionally vary alpha independently: `font.background.stroke.alpha`
- Text box **stroke width**:
- `font.background.stroke.width`
- Values in pixels, as with `font.stroke.width`
- e.g. `font.background.stroke.width: 2px` (explicit) or `font.background.stroke.width: 2` (implicit)
- Defaults to `1px` when `font.background.stroke.color` is not null
- Text background fill and stroke are both incorporated into the label's collision box.
**Examples**
Fill only:
```
draw:
text:
...
font: …
```
> Add support for text highlight boxes + underlines

- src/tile/tile_manager.js
The visibility of over/underzoomed "proxy tiles" when the current view tiles aren't done loading was determined by the instantaneous view state: +1 when zooming in, -1 when zooming out. This assumed that ZOOM-1 tiles are loaded when zooming in, and ZOOM+1 tiles are loaded when zooming out. This assumption works fine when slowly paging through zooms in one direction, letting each layer load at a time, but breaks down if the direction of the scroll is reversed within a zoom level that isn't done loading.
Comparison video of before/after, that flies 4 zoom levels in in 300ms, and 2 levels out in another 300ms:
[Video Link (mp4)](https://bdon.s3.amazonaws.com/tileload.mp4)
This doesn't solve all visibility issues related to flickering tiles I've noticed - may demand a larger rethinking of how …
> proxy tiles don't depend on scroll direction

- src/leaflet_layer.js
This is more similar to the behavior of Leaflet raster tiles where each individual tile layer can have an attribution. Because a TangramLayer can use multiple tile sources, this lets the attribution for each source be specified in YAML, and then these are added together in the case that no explicit 'attribution' prop is passed to LeafletLayer.
> If no explicit attribution in leafletLayer, use attribution in YAML sources

- karma.conf.js
- src/scene/globals.js
- src/scene/scene.js
- src/scene/scene_bundle.js
- src/scene/scene_loader.js
- src/utils/props.js
Resolve named textures using final merged scene. This fixes cases where named textures defined via global properties in imported scenes would be interpreted as URLs, if the texture name was not yet defined in the imported scene, but which will be defined in the final merged scene (e.g. the texture name is defined by an ancestor/importing scene, but not the descendant/imported scene where it is used).
See https://github.com/tangrams/tangram/issues/748 for issue, and https://github.com/tangrams/tangram-es/pull/2201 for Tangram ES fix.
> Resolve texture imports using final merged scene
